export const SYSTEM_SETTING_CATEGORIES = [
  'GENERAL',
  'SECURITY',
  'RUNTIME',
  'OBSERVABILITY',
  'RETENTION',
  'INTEGRATION',
] as const;

export const SYSTEM_SETTING_CATEGORY_LABELS: Record<(typeof SYSTEM_SETTING_CATEGORIES)[number], string> = {
  GENERAL: '基础',
  SECURITY: '安全',
  RUNTIME: '运行时',
  OBSERVABILITY: '观测',
  RETENTION: '数据保留',
  INTEGRATION: '外部集成',
};

export const SYSTEM_SETTING_VALUE_TYPES = ['STRING', 'NUMBER', 'BOOLEAN', 'JSON', 'SELECT'] as const;
export const SYSTEM_SETTING_MUTATION_STATUSES = ['ACTIVE', 'DISABLED'] as const;
export const SYSTEM_SETTING_LIST_STATUSES = ['ACTIVE', 'DISABLED', 'DELETED'] as const;

export const DEFAULT_SYSTEM_SETTINGS = [
  {
    category: 'GENERAL',
    key: 'default_locale',
    name: '默认语言',
    description: '控制台默认语言与本地化展示。',
    value: 'zh-CN',
    defaultValue: 'zh-CN',
    valueType: 'SELECT',
    options: [
      { label: '简体中文', value: 'zh-CN' },
      { label: '英文', value: 'en-US' },
    ],
    isSecret: false,
    sortOrder: 10,
  },
  {
    category: 'GENERAL',
    key: 'workspace_name',
    name: '工作区名称',
    description: '展示在控制台和外部调用响应里的工作区名称。',
    value: '企业 Agent 平台',
    defaultValue: '企业 Agent 平台',
    valueType: 'STRING',
    options: null,
    isSecret: false,
    sortOrder: 20,
  },
  {
    category: 'SECURITY',
    key: 'session_timeout_minutes',
    name: '会话超时分钟数',
    description: '用户长期无操作后的登录会话过期时间。',
    value: 120,
    defaultValue: 120,
    valueType: 'NUMBER',
    options: null,
    isSecret: false,
    sortOrder: 10,
  },
  {
    category: 'SECURITY',
    key: 'api_key_ip_allowlist_required',
    name: 'API Key 必须配置 IP 白名单',
    description: '启用后新建外部调用密钥必须提供 IP 白名单。',
    value: false,
    defaultValue: false,
    valueType: 'BOOLEAN',
    options: null,
    isSecret: false,
    sortOrder: 20,
  },
  {
    category: 'RUNTIME',
    key: 'runtime_stream_enabled',
    name: '运行时流式输出',
    description: '控制 Agent Runtime 是否默认允许 SSE 流式响应。',
    value: true,
    defaultValue: true,
    valueType: 'BOOLEAN',
    options: null,
    isSecret: false,
    sortOrder: 10,
  },
  {
    category: 'RUNTIME',
    key: 'runtime_default_temperature',
    name: '默认温度',
    description: 'Agent 未单独设置模型温度时使用的默认值。',
    value: 0.4,
    defaultValue: 0.4,
    valueType: 'NUMBER',
    options: null,
    isSecret: false,
    sortOrder: 20,
  },
  {
    category: 'OBSERVABILITY',
    key: 'trace_sample_rate',
    name: 'Trace 采样率',
    description: 'OpenTelemetry 链路追踪采样比例，取值范围 0 到 1。',
    value: 1,
    defaultValue: 1,
    valueType: 'NUMBER',
    options: null,
    isSecret: false,
    sortOrder: 10,
  },
  {
    category: 'OBSERVABILITY',
    key: 'monitor_error_alert_enabled',
    name: '异常告警开关',
    description: '启用后监控中心会记录并展示异常告警信号。',
    value: true,
    defaultValue: true,
    valueType: 'BOOLEAN',
    options: null,
    isSecret: false,
    sortOrder: 20,
  },
  {
    category: 'RETENTION',
    key: 'audit_retention_days',
    name: '审计日志保留天数',
    description: '审计与操作日志建议保留时长。',
    value: 180,
    defaultValue: 180,
    valueType: 'NUMBER',
    options: null,
    isSecret: false,
    sortOrder: 10,
  },
  {
    category: 'RETENTION',
    key: 'conversation_retention_days',
    name: '会话记录保留天数',
    description: '会话与运行记录建议保留时长。',
    value: 90,
    defaultValue: 90,
    valueType: 'NUMBER',
    options: null,
    isSecret: false,
    sortOrder: 20,
  },
  {
    category: 'INTEGRATION',
    key: 'external_webhook_url',
    name: '外部 Webhook 地址',
    description: '用于后续集成审批、告警或自动化通知的 Webhook 地址。',
    value: '',
    defaultValue: '',
    valueType: 'STRING',
    options: null,
    isSecret: true,
    sortOrder: 10,
  },
  {
    category: 'INTEGRATION',
    key: 'minio_public_base_url',
    name: '文件公开访问基址',
    description: '用于生成对象存储文件预览或下载链接的外部基址。',
    value: '',
    defaultValue: '',
    valueType: 'STRING',
    options: null,
    isSecret: false,
    sortOrder: 20,
  },
] as const;
