export const SYSTEM_SETTING_CATEGORIES = [
  'GENERAL',
  'SECURITY',
  'RUNTIME',
  'OBSERVABILITY',
  'NOTIFICATION',
  'RETENTION',
  'INTEGRATION',
] as const;

export const SYSTEM_SETTING_CATEGORY_LABELS: Record<(typeof SYSTEM_SETTING_CATEGORIES)[number], string> = {
  GENERAL: '基础',
  SECURITY: '安全',
  RUNTIME: '运行时',
  OBSERVABILITY: '观测',
  NOTIFICATION: '通知策略',
  RETENTION: '数据保留',
  INTEGRATION: '外部集成',
};

export const SYSTEM_SETTING_VALUE_TYPES = ['STRING', 'NUMBER', 'BOOLEAN', 'JSON', 'SELECT'] as const;
export const SYSTEM_SETTING_MUTATION_STATUSES = ['ACTIVE', 'DISABLED'] as const;
export const SYSTEM_SETTING_LIST_STATUSES = ['ACTIVE', 'DISABLED', 'DELETED'] as const;

export const DEFAULT_SYSTEM_SETTINGS = [
  {
    category: 'GENERAL',
    key: 'default_locale',
    name: '默认语言',
    description: '控制台默认语言与本地化展示。',
    value: 'zh-CN',
    defaultValue: 'zh-CN',
    valueType: 'SELECT',
    options: [
      { label: '简体中文', value: 'zh-CN' },
      { label: '英文', value: 'en-US' },
    ],
    isSecret: false,
    sortOrder: 10,
  },
  {
    category: 'GENERAL',
    key: 'workspace_name',
    name: '工作区名称',
    description: '展示在控制台和外部调用响应里的工作区名称。',
    value: '企业 Agent 平台',
    defaultValue: '企业 Agent 平台',
    valueType: 'STRING',
    options: null,
    isSecret: false,
    sortOrder: 20,
  },
  {
    category: 'SECURITY',
    key: 'session_timeout_minutes',
    name: '会话超时分钟数',
    description: '用户长期无操作后的登录会话过期时间。',
    value: 120,
    defaultValue: 120,
    valueType: 'NUMBER',
    options: null,
    isSecret: false,
    sortOrder: 10,
  },
  {
    category: 'SECURITY',
    key: 'api_key_ip_allowlist_required',
    name: 'API Key 必须配置 IP 白名单',
    description: '启用后新建外部调用密钥必须提供 IP 白名单。',
    value: false,
    defaultValue: false,
    valueType: 'BOOLEAN',
    options: null,
    isSecret: false,
    sortOrder: 20,
  },
  {
    category: 'RUNTIME',
    key: 'runtime_stream_enabled',
    name: '运行时流式输出',
    description: '控制 Agent Runtime 是否默认允许 SSE 流式响应。',
    value: true,
    defaultValue: true,
    valueType: 'BOOLEAN',
    options: null,
    isSecret: false,
    sortOrder: 10,
  },
  {
    category: 'RUNTIME',
    key: 'runtime_default_temperature',
    name: '默认温度',
    description: 'Agent 未单独设置模型温度时使用的默认值。',
    value: 0.4,
    defaultValue: 0.4,
    valueType: 'NUMBER',
    options: null,
    isSecret: false,
    sortOrder: 20,
  },
  {
    category: 'OBSERVABILITY',
    key: 'trace_sample_rate',
    name: 'Trace 采样率',
    description: 'OpenTelemetry 链路追踪采样比例，取值范围 0 到 1。',
    value: 1,
    defaultValue: 1,
    valueType: 'NUMBER',
    options: null,
    isSecret: false,
    sortOrder: 10,
  },
  {
    category: 'OBSERVABILITY',
    key: 'monitor_error_alert_enabled',
    name: '异常告警开关',
    description: '启用后监控中心会记录并展示异常告警信号。',
    value: true,
    defaultValue: true,
    valueType: 'BOOLEAN',
    options: null,
    isSecret: false,
    sortOrder: 20,
  },
  {
    category: 'NOTIFICATION',
    key: 'alert_notification_auto_notify_enabled',
    name: '告警首发自动通知',
    description: '启用后后台任务会自动通知 SLA 死信归档删除审批运营告警。',
    value: true,
    defaultValue: true,
    valueType: 'BOOLEAN',
    options: null,
    isSecret: false,
    sortOrder: 10,
  },
  {
    category: 'NOTIFICATION',
    key: 'alert_notification_auto_notify_interval_ms',
    name: '首发通知扫描间隔',
    description: '告警首发自动通知任务的扫描间隔，单位毫秒。',
    value: 60000,
    defaultValue: 60000,
    valueType: 'NUMBER',
    options: null,
    isSecret: false,
    sortOrder: 20,
  },
  {
    category: 'NOTIFICATION',
    key: 'alert_notification_auto_notify_batch_size',
    name: '单批通知数量',
    description: '每次首发自动通知任务最多处理的运营告警数量。',
    value: 8,
    defaultValue: 8,
    valueType: 'NUMBER',
    options: null,
    isSecret: false,
    sortOrder: 30,
  },
  {
    category: 'NOTIFICATION',
    key: 'alert_notification_auto_retry_enabled',
    name: '告警通知自动重试',
    description: '启用后后台任务会自动扫描失败或部分成功的告警通知投递。',
    value: true,
    defaultValue: true,
    valueType: 'BOOLEAN',
    options: null,
    isSecret: false,
    sortOrder: 40,
  },
  {
    category: 'NOTIFICATION',
    key: 'alert_notification_retry_interval_ms',
    name: '自动重试扫描间隔',
    description: '告警通知自动重试任务的扫描间隔，单位毫秒。',
    value: 60000,
    defaultValue: 60000,
    valueType: 'NUMBER',
    options: null,
    isSecret: false,
    sortOrder: 50,
  },
  {
    category: 'NOTIFICATION',
    key: 'alert_notification_retry_batch_size',
    name: '单批重试数量',
    description: '每次自动重试任务最多处理的告警通知投递记录数。',
    value: 8,
    defaultValue: 8,
    valueType: 'NUMBER',
    options: null,
    isSecret: false,
    sortOrder: 60,
  },
  {
    category: 'NOTIFICATION',
    key: 'alert_notification_max_retry_count',
    name: '最大重试次数',
    description: '单条告警通知投递最多允许自动重试的次数。',
    value: 3,
    defaultValue: 3,
    valueType: 'NUMBER',
    options: null,
    isSecret: false,
    sortOrder: 70,
  },
  {
    category: 'NOTIFICATION',
    key: 'alert_notification_retry_backoff_seconds',
    name: '重试退避秒数',
    description: '投递失败后至少等待多少秒才允许进入自动重试。',
    value: 60,
    defaultValue: 60,
    valueType: 'NUMBER',
    options: null,
    isSecret: false,
    sortOrder: 110,
  },
  {
    category: 'NOTIFICATION',
    key: 'alert_notification_lookback_hours',
    name: '重试回看小时数',
    description: '自动重试任务扫描最近多少小时内的告警通知投递记录。',
    value: 24,
    defaultValue: 24,
    valueType: 'NUMBER',
    options: null,
    isSecret: false,
    sortOrder: 120,
  },
  {
    category: 'NOTIFICATION',
    key: 'operation_alert_sla_enabled',
    name: '审批归档告警 SLA',
    description: '启用后安全中心会计算审批与归档运营告警的处理时限。',
    value: true,
    defaultValue: true,
    valueType: 'BOOLEAN',
    options: null,
    isSecret: false,
    sortOrder: 100,
  },
  {
    category: 'NOTIFICATION',
    key: 'operation_alert_sla_scan_interval_ms',
    name: 'SLA 扫描间隔',
    description: '审批与归档告警 SLA 自动升级任务的扫描间隔，单位毫秒。',
    value: 60000,
    defaultValue: 60000,
    valueType: 'NUMBER',
    options: null,
    isSecret: false,
    sortOrder: 80,
  },
  {
    category: 'NOTIFICATION',
    key: 'operation_alert_sla_due_minutes',
    name: 'SLA 到期分钟数',
    description: '审批与归档运营告警触发后允许处理的最长分钟数。',
    value: 120,
    defaultValue: 120,
    valueType: 'NUMBER',
    options: null,
    isSecret: false,
    sortOrder: 90,
  },
  {
    category: 'NOTIFICATION',
    key: 'operation_alert_sla_warning_minutes',
    name: 'SLA 预警分钟数',
    description: '距离 SLA 到期多少分钟内进入临近超时状态。',
    value: 30,
    defaultValue: 30,
    valueType: 'NUMBER',
    options: null,
    isSecret: false,
    sortOrder: 130,
  },
  {
    category: 'NOTIFICATION',
    key: 'operation_alert_sla_auto_escalate_enabled',
    name: 'SLA 超时自动升级',
    description: '启用后超过 SLA 且未关闭的审批与归档告警会自动升级。',
    value: true,
    defaultValue: true,
    valueType: 'BOOLEAN',
    options: null,
    isSecret: false,
    sortOrder: 140,
  },
  {
    category: 'NOTIFICATION',
    key: 'operation_alert_sla_lookback_hours',
    name: 'SLA 回看小时数',
    description: 'SLA 任务保留的策略回看窗口，后续迁移 Temporal 时用于裁剪扫描范围。',
    value: 24,
    defaultValue: 24,
    valueType: 'NUMBER',
    options: null,
    isSecret: false,
    sortOrder: 150,
  },
  {
    category: 'NOTIFICATION',
    key: 'operation_alert_sla_subscription_policy',
    name: 'SLA 超时订阅策略',
    description: '配置审批与归档告警 SLA 超时通知的渠道和订阅目标。',
    value: {
      enabled: true,
      channels: ['IN_APP', 'WEBHOOK'],
      default_targets: ['安全管理员'],
      high_risk_targets: ['租户管理员', '安全管理员', '审计员'],
      archive_targets: ['安全管理员', '审计员'],
    },
    defaultValue: {
      enabled: true,
      channels: ['IN_APP', 'WEBHOOK'],
      default_targets: ['安全管理员'],
      high_risk_targets: ['租户管理员', '安全管理员', '审计员'],
      archive_targets: ['安全管理员', '审计员'],
    },
    valueType: 'JSON',
    options: null,
    isSecret: false,
    sortOrder: 160,
  },
  {
    category: 'NOTIFICATION',
    key: 'operation_alert_sla_notification_auto_retry_enabled',
    name: 'SLA 通知自动重试',
    description: '启用后后台任务会自动扫描失败或部分成功的 SLA 超时通知投递。',
    value: true,
    defaultValue: true,
    valueType: 'BOOLEAN',
    options: null,
    isSecret: false,
    sortOrder: 170,
  },
  {
    category: 'NOTIFICATION',
    key: 'operation_alert_sla_notification_retry_interval_ms',
    name: 'SLA 通知重试扫描间隔',
    description: 'SLA 超时通知自动重试任务的扫描间隔，单位毫秒。',
    value: 60000,
    defaultValue: 60000,
    valueType: 'NUMBER',
    options: null,
    isSecret: false,
    sortOrder: 180,
  },
  {
    category: 'NOTIFICATION',
    key: 'operation_alert_sla_notification_retry_batch_size',
    name: 'SLA 通知单批重试数量',
    description: '每次 SLA 超时通知自动重试任务最多处理的投递记录数。',
    value: 8,
    defaultValue: 8,
    valueType: 'NUMBER',
    options: null,
    isSecret: false,
    sortOrder: 190,
  },
  {
    category: 'NOTIFICATION',
    key: 'operation_alert_sla_notification_max_retry_count',
    name: 'SLA 通知最大重试次数',
    description: '单条 SLA 超时通知投递最多允许自动重试的次数，超过后进入死信视图。',
    value: 3,
    defaultValue: 3,
    valueType: 'NUMBER',
    options: null,
    isSecret: false,
    sortOrder: 200,
  },
  {
    category: 'NOTIFICATION',
    key: 'operation_alert_sla_notification_retry_backoff_seconds',
    name: 'SLA 通知重试退避秒数',
    description: 'SLA 超时通知投递失败后至少等待多少秒才允许进入自动重试。',
    value: 60,
    defaultValue: 60,
    valueType: 'NUMBER',
    options: null,
    isSecret: false,
    sortOrder: 210,
  },
  {
    category: 'NOTIFICATION',
    key: 'operation_alert_sla_notification_lookback_hours',
    name: 'SLA 通知重试回看小时数',
    description: 'SLA 超时通知自动重试任务扫描最近多少小时内的投递记录。',
    value: 24,
    defaultValue: 24,
    valueType: 'NUMBER',
    options: null,
    isSecret: false,
    sortOrder: 220,
  },
  {
    category: 'RETENTION',
    key: 'audit_retention_days',
    name: '审计日志保留天数',
    description: '审计与操作日志建议保留时长。',
    value: 180,
    defaultValue: 180,
    valueType: 'NUMBER',
    options: null,
    isSecret: false,
    sortOrder: 10,
  },
  {
    category: 'RETENTION',
    key: 'conversation_retention_days',
    name: '会话记录保留天数',
    description: '会话与运行记录建议保留时长。',
    value: 90,
    defaultValue: 90,
    valueType: 'NUMBER',
    options: null,
    isSecret: false,
    sortOrder: 20,
  },
  {
    category: 'INTEGRATION',
    key: 'external_webhook_url',
    name: '外部 Webhook 地址',
    description: '用于后续集成审批、告警或自动化通知的 Webhook 地址。',
    value: '',
    defaultValue: '',
    valueType: 'STRING',
    options: null,
    isSecret: true,
    sortOrder: 10,
  },
  {
    category: 'INTEGRATION',
    key: 'minio_public_base_url',
    name: '文件公开访问基址',
    description: '用于生成对象存储文件预览或下载链接的外部基址。',
    value: '',
    defaultValue: '',
    valueType: 'STRING',
    options: null,
    isSecret: false,
    sortOrder: 20,
  },
] as const;
