import { IsIn, IsOptional, IsString } from 'class-validator';

const SECURITY_OPERATION_ALERT_NOTIFICATION_TASK_RECOVERY_ACTIONS = ['ACKNOWLEDGE', 'IGNORE', 'RESOLVE'] as const;
const SECURITY_OPERATION_ALERT_NOTIFICATION_TASK_RECOVERY_STATUSES = ['ACKNOWLEDGED', 'IGNORED', 'RESOLVED'] as const;
const SECURITY_OPERATION_ALERT_NOTIFICATION_TASK_RECOVERY_REASONS = [
  'WEBHOOK_NOT_CONFIGURED',
  'WEBHOOK_DELIVERY_FAILED',
  'AUTO_NOTIFY_DISABLED',
  'AUTO_RETRY_DISABLED',
  'CONSECUTIVE_FAILURES',
  'HIGH_FAILURE_RATE',
] as const;
const SECURITY_OPERATION_ALERT_NOTIFICATION_TASK_RECOVERY_FAILURE_SOURCES = [
  'SLA_DEAD_LETTER_ARCHIVE_DELETE',
  'NOTIFICATION_TASK_RECOVERY_AUDIT_ARCHIVE_DELETE',
  'MIXED',
  'UNKNOWN',
] as const;

export class ListSecurityOperationAlertNotificationTaskRecoveryAuditsDto {
  @IsOptional()
  @IsIn(SECURITY_OPERATION_ALERT_NOTIFICATION_TASK_RECOVERY_ACTIONS)
  action?: 'ACKNOWLEDGE' | 'IGNORE' | 'RESOLVE';

  @IsOptional()
  @IsIn(SECURITY_OPERATION_ALERT_NOTIFICATION_TASK_RECOVERY_STATUSES)
  status?: 'ACKNOWLEDGED' | 'IGNORED' | 'RESOLVED';

  @IsOptional()
  @IsIn(SECURITY_OPERATION_ALERT_NOTIFICATION_TASK_RECOVERY_REASONS)
  reason_code?:
    | 'WEBHOOK_NOT_CONFIGURED'
    | 'WEBHOOK_DELIVERY_FAILED'
    | 'AUTO_NOTIFY_DISABLED'
    | 'AUTO_RETRY_DISABLED'
    | 'CONSECUTIVE_FAILURES'
    | 'HIGH_FAILURE_RATE';

  @IsOptional()
  @IsIn(SECURITY_OPERATION_ALERT_NOTIFICATION_TASK_RECOVERY_FAILURE_SOURCES)
  failure_source?:
    | 'SLA_DEAD_LETTER_ARCHIVE_DELETE'
    | 'NOTIFICATION_TASK_RECOVERY_AUDIT_ARCHIVE_DELETE'
    | 'MIXED'
    | 'UNKNOWN';

  @IsOptional()
  @IsString()
  keyword?: string;
}
