export type ModuleStatus = 'ready' | 'planned' | 'mock';

export interface MetricPreview {
  label: string;
  value: string;
  helper: string;
}

export interface ModuleSpec {
  key: string;
  title: string;
  navTitle: string;
  href: string;
  description: string;
  permission: string;
  status: ModuleStatus;
  primaryAction: string;
  metrics: MetricPreview[];
  filters: string[];
  columns: string[];
  detailSections: string[];
  rowActions: string[];
  emptyTitle: string;
  emptyDescription: string;
}

export const moduleSpecs: ModuleSpec[] = [
  {
    key: 'agents',
    title: '智能体配置中心',
    navTitle: '智能体',
    href: '/agents',
    description: '创建、配置、测试、版本化、发布、停用、复制并审计企业智能体。',
    permission: 'agent:agent:view',
    status: 'ready',
    primaryAction: '新建智能体',
    metrics: [
      { label: '智能体', value: '0', helper: 'M03 数据源' },
      { label: '已发布', value: '0', helper: '发布状态' },
      { label: '草稿', value: '0', helper: '草稿状态' },
      { label: '已停用', value: '0', helper: '停用状态' },
    ],
    filters: ['关键词：名称/编码/描述', '状态', '分类', '负责人'],
    columns: ['名称', '编码', '状态', '版本', '默认模型', '更新时间', '负责人', '操作'],
    detailSections: [
      '基础信息',
      '运行配置',
      '模型绑定',
      '提示词绑定',
      '知识库绑定',
      '工具绑定',
      '版本',
      '会话测试',
      '审计记录',
    ],
    rowActions: ['编辑', '复制', '启用', '停用', '删除', '详情'],
    emptyTitle: '暂无智能体',
    emptyDescription: '创建智能体，并基于控制接口数据表管理版本化发布流程。',
  },
  {
    key: 'agent_teams',
    title: 'Agent 协作中心',
    navTitle: 'Agent 协作',
    href: '/agent-teams',
    description: '配置多 Agent 团队、成员职责、执行顺序、运行轨迹、接力记录和人工反馈。',
    permission: 'agent:team:view',
    status: 'ready',
    primaryAction: '新建协作团队',
    metrics: [
      { label: '协作团队', value: '0', helper: '团队配置' },
      { label: '启用团队', value: '0', helper: 'ACTIVE' },
      { label: '运行中', value: '0', helper: '团队任务' },
      { label: '等待接管', value: '0', helper: '人工接力' },
    ],
    filters: ['关键词：名称/编码/描述', '状态', '协作模式', '负责人'],
    columns: ['团队', '状态', '协作模式', '成员', '最近运行', '负责人', '更新时间', '操作'],
    detailSections: [
      '团队基础信息',
      '成员职责',
      '运行时间线',
      '接力记录',
      '反馈记录',
      'Trace 关联',
      '资源授权提示',
    ],
    rowActions: ['详情', '编辑', '添加成员', '启动任务', '发起接力', '反馈', '归档'],
    emptyTitle: '暂无协作团队',
    emptyDescription: '创建团队并添加 Agent 成员后，可以启动团队任务并查看多 Agent 协作台账。',
  },
  {
    key: 'role_scenarios',
    title: '岗位场景编排中心',
    navTitle: '岗位场景',
    href: '/role-scenarios',
    description: '把岗位、流程、Agent、Skill、知识库、工具、提示词和验收标准编排为可交付 AI 场景包。',
    permission: 'scenario:package:view',
    status: 'ready',
    primaryAction: '新建场景包',
    metrics: [
      { label: '场景包', value: '0', helper: 'M120 数据源' },
      { label: '高价值', value: '0', helper: '80 分以上' },
      { label: '试点中', value: '0', helper: 'PILOTING' },
      { label: '资产齐套', value: '0', helper: '五类资产' },
    ],
    filters: ['关键词：场景/岗位/痛点/流程', '场景类型', '状态', '优先级', '负责人'],
    columns: ['场景包', '岗位/部门', '状态', '价值评分', '痛点预览', '流程预览', '关联资产', '负责人', '更新时间', '操作'],
    detailSections: [
      '基础信息',
      '业务痛点',
      '业务目标',
      '流程编排',
      '预期成果',
      '样板成果',
      '验收标准',
      'ROI 指标',
      '关联资产',
      '备注',
    ],
    rowActions: ['详情', '编辑', '归档'],
    emptyTitle: '暂无岗位场景',
    emptyDescription: '创建岗位场景包后，可以在详情页查看完整流程、样板成果、验收标准和关联资产。',
  },
  {
    key: 'solution_packages',
    title: 'AI 落地方案包中心',
    navTitle: '落地方案',
    href: '/solution-packages',
    description: '把客户评估和岗位场景转成可交付的方案摘要、交付路线图、验收计划、ROI 摘要和商务推进策略。',
    permission: 'solution:package:view',
    status: 'ready',
    primaryAction: '新建方案包',
    metrics: [
      { label: '方案包', value: '0', helper: 'M121 数据源' },
      { label: '高完整度', value: '0', helper: '85 分以上' },
      { label: '交付中', value: '0', helper: 'DELIVERING' },
      { label: '资源绑定', value: '0', helper: '评估 + 场景' },
    ],
    filters: ['关键词：客户/方案/路线图/ROI', '客户类型', '方案阶段', '状态', '优先级', '负责人'],
    columns: ['方案包', '客户', '阶段/状态', '评分', '方案摘要', '路线图预览', 'ROI 预览', '关联资源', '负责人', '更新时间', '操作'],
    detailSections: [
      '方案摘要',
      '业务目标',
      '落地范围',
      '场景蓝图',
      '交付路线图',
      '验收计划',
      'ROI 摘要',
      '风险缓释',
      '商务推进',
      '下一里程碑',
      '关联资源',
      '备注',
    ],
    rowActions: ['详情', '编辑', '归档'],
    emptyTitle: '暂无落地方案',
    emptyDescription: '创建方案包后，可以在详情页查看完整交付路线图、验收计划、ROI、风险和关联资源。',
  },
  {
    key: 'delivery_reviews',
    title: '交付验收复盘中心',
    navTitle: '验收复盘',
    href: '/delivery-reviews',
    description: '承接落地方案包，记录交付验收、问题复盘、改进行动、扩展计划和可复用资产。',
    permission: 'delivery:review:view',
    status: 'ready',
    primaryAction: '新建复盘',
    metrics: [
      { label: '验收复盘', value: '0', helper: 'M122 数据源' },
      { label: '高分验收', value: '0', helper: '85 分以上' },
      { label: '已完成', value: '0', helper: 'COMPLETED' },
      { label: '待改进', value: '0', helper: 'ACTION_REQUIRED' },
    ],
    filters: ['关键词：客户/结论/问题/扩展', '复盘阶段', '验收结果', '复盘状态', '满意度', '负责人', '方案包'],
    columns: ['复盘', '客户', '阶段/结果/状态', '评分', '验收结论', '问题预览', '关联方案包', '负责人', '复盘时间', '操作'],
    detailSections: [
      '已交付范围',
      '验收结论',
      '问题复盘',
      '改进行动',
      '扩展计划',
      '可复用资产',
      '下一步动作',
      '关联方案包',
      '标签备注',
    ],
    rowActions: ['详情', '编辑', '归档'],
    emptyTitle: '暂无验收复盘',
    emptyDescription: '创建复盘后，可以在详情页查看完整验收、问题、改进、扩展和可复用资产。',
  },
  {
    key: 'channels',
    title: '全渠道发布中心',
    navTitle: '发布渠道',
    href: '/channels',
    description: '管理 Agent 在 Web 组件、开放 API、企业微信、钉钉、飞书、Slack 和自定义 Webhook 的发布配置、启停、健康检查和用量观测。',
    permission: 'channel:publish:view',
    status: 'ready',
    primaryAction: '新建发布渠道',
    metrics: [
      { label: '发布渠道', value: '0', helper: 'Agent 渠道配置' },
      { label: '启用渠道', value: '0', helper: 'ACTIVE' },
      { label: '异常渠道', value: '0', helper: 'ERROR / UNAVAILABLE' },
      { label: '24h 请求', value: '0', helper: '渠道用量事件' },
    ],
    filters: ['关键词：渠道/Agent/地址', '渠道类型', '发布状态', '健康状态'],
    columns: ['渠道', 'Agent', '发布状态', '健康状态', '入口地址', '24h 请求', '成功率', '更新时间', '操作'],
    detailSections: [
      '渠道总览',
      '渠道清单',
      '渠道详情',
      '新建与编辑',
      '启用停用',
      '健康检查',
      '渠道类型分布',
      '最近事件',
      '资源授权提示',
    ],
    rowActions: ['详情', '编辑', '启用', '停用', '健康检查', '复制入口'],
    emptyTitle: '暂无发布渠道',
    emptyDescription: '选择已发布 Agent 后配置发布渠道，外部入口、回调地址和健康状态会在这里集中管理。',
  },
  {
    key: 'customer_assessments',
    title: '客户分层评估中心',
    navTitle: '客户评估',
    href: '/customer-assessments',
    description: '基于客户分层和前期六问判断，沉淀 AI 落地准备度、建议打法、风险提示和下一步动作。',
    permission: 'customer:assessment:view',
    status: 'ready',
    primaryAction: '新建客户评估',
    metrics: [
      { label: '客户评估', value: '0', helper: 'M119 数据源' },
      { label: '高准备度', value: '0', helper: '80 分以上' },
      { label: '任务型客户', value: '0', helper: '采购/交付导向' },
      { label: '已确认', value: '0', helper: 'QUALIFIED' },
    ],
    filters: ['关键词：客户/行业/目标/风险', '客户类型', '决策阶段', '评估状态', '负责人'],
    columns: ['客户', '类型', '阶段', '状态', '准备度', '目标预览', '建议预览', '负责人', '更新时间', '操作'],
    detailSections: [
      '基础信息',
      '六问判断',
      '六问评分',
      '准备度结果',
      '建议打法',
      '风险提示',
      '下一步动作',
      '操作记录',
    ],
    rowActions: ['详情', '编辑', '归档'],
    emptyTitle: '暂无客户评估',
    emptyDescription: '新建客户评估后，可以在详情页维护完整六问判断和客户落地策略。',
  },
  {
    key: 'plugins',
    title: '插件生态中心',
    navTitle: '插件生态',
    href: '/plugins',
    description: '管理插件市场、安装实例、启停、升级、菜单注入、Hook 和审计轨迹。',
    permission: 'plugin:center:view',
    status: 'ready',
    primaryAction: '查看插件市场',
    metrics: [
      { label: '插件', value: '0', helper: '市场与安装' },
      { label: '已安装', value: '0', helper: '租户实例' },
      { label: '已启用', value: '0', helper: 'ACTIVE' },
      { label: '待审核', value: '0', helper: '安全审核' },
    ],
    filters: ['关键词：名称/编码/提供方', '状态', '安装状态', '风险等级'],
    columns: ['插件', '编码', '版本', '安装状态', '菜单注入', '风险等级', '更新时间', '操作'],
    detailSections: [
      '市场概览',
      '插件详情',
      '版本记录',
      '安装向导',
      '菜单注入',
      'Hook 绑定',
      '权限预览',
      '审计记录',
    ],
    rowActions: ['安装', '启用', '停用', '升级', '审计', '详情'],
    emptyTitle: '暂无插件',
    emptyDescription: '安装已审核插件后，可为租户注入菜单、配置 Hook 并记录完整审计。',
  },
  {
    key: 'prompts',
    title: '提示词中心',
    navTitle: '提示词',
    href: '/prompts',
    description: '管理提示词模板、变量、版本、测试、回滚和智能体引用。',
    permission: 'prompt:template:view',
    status: 'ready',
    primaryAction: '新建提示词',
    metrics: [
      { label: '模板', value: '0', helper: 'M05 数据源' },
      { label: '已发布', value: '0', helper: '不可变版本' },
      { label: '草稿', value: '0', helper: '可编辑状态' },
      { label: '测试', value: '0', helper: '提示词测试记录' },
    ],
    filters: ['关键词：名称/编码/内容', '类型', '状态', '创建人'],
    columns: ['名称', '编码', '类型', '状态', '版本', '更新时间', '操作'],
    detailSections: [
      '基础信息',
      '提示词编辑器',
      '变量',
      '版本',
      '测试面板',
      '智能体引用',
      '审计记录',
    ],
    rowActions: ['编辑', '复制', '发布', '回滚', '删除', '测试'],
    emptyTitle: '暂无提示词模板',
    emptyDescription: '创建提示词模板、变量、不可变版本、渲染检查和智能体引用。',
  },
  {
    key: 'models',
    title: '模型中心',
    navTitle: '模型',
    href: '/models',
    description: '管理供应商、模型配置、加密接口密钥、成本、限流和调用日志。',
    permission: 'model:config:view',
    status: 'ready',
    primaryAction: '新建供应商',
    metrics: [
      { label: '供应商', value: '0', helper: 'M04 数据源' },
      { label: '启用模型', value: '0', helper: '可绑定' },
      { label: '今日调用', value: '0', helper: '模型调用日志' },
      { label: '今日成本', value: '$0.00', helper: '成本规则' },
    ],
    filters: ['关键词：供应商/模型', '供应商类型', '能力', '状态'],
    columns: ['供应商', '模型', '能力', '上下文', '输入价格', '输出价格', '限流', '状态'],
    detailSections: [
      '供应商资料',
      '脱敏接口密钥',
      '能力',
      '成本规则',
      '限流',
      '调用测试面板',
      '调用日志',
    ],
    rowActions: ['编辑', '停用', '删除', '测试', '详情'],
    emptyTitle: '暂无模型供应商',
    emptyDescription: '配置 OpenAI 兼容供应商、脱敏接口密钥、模型、价格和调用测试。',
  },
  {
    key: 'knowledge',
    title: '知识库中心',
    navTitle: '知识库',
    href: '/knowledge',
    description: '管理知识库、文档、切片、处理任务、检索测试和智能体绑定。',
    permission: 'knowledge:base:view',
    status: 'ready',
    primaryAction: '新建知识库',
    metrics: [
      { label: '知识库', value: '0', helper: 'M06 数据源' },
      { label: '文档', value: '0', helper: 'PostgreSQL 元数据' },
      { label: '切片', value: '0', helper: 'PostgreSQL 切片' },
      { label: '失败任务', value: '0', helper: '处理任务' },
    ],
    filters: ['关键词：名称/编码/描述', '状态', '可见范围', '更新时间'],
    columns: ['名称', '编码', '文档', '切片', '状态', '更新时间', '操作'],
    detailSections: [
      '基础信息',
      '文档列表',
      '上传面板',
      '文档预览',
      '切片',
      '检索测试',
      '处理任务',
      '智能体绑定',
    ],
    rowActions: ['编辑', '上传', '检索测试', '重建索引', '删除', '详情'],
    emptyTitle: '暂无知识库',
    emptyDescription: '上传文本或 Markdown 文档内容，生成切片、重建索引并运行检索测试。',
  },
  {
    key: 'storage',
    title: '文件存储中心',
    navTitle: '文件存储',
    href: '/storage',
    description: '管理 MinIO 存储设置、桶初始化、租户文件上传、下载和删除。',
    permission: 'storage:object:view',
    status: 'ready',
    primaryAction: '上传文件',
    metrics: [
      { label: '对象', value: '0', helper: 'MinIO 对象' },
      { label: '容量', value: '0 B', helper: '租户前缀' },
      { label: '桶状态', value: '未检查', helper: 'aiaget-files' },
      { label: '连接', value: '未知', helper: 'MinIO' },
    ],
    filters: ['关键词：文件名/路径', '目录前缀', '更新时间'],
    columns: ['文件名', '目录', '大小', 'ETag', '更新时间', '操作'],
    detailSections: [
      '存储设置',
      '连接状态',
      '桶初始化',
      '上传文件',
      '文件列表',
      '下载链接',
      '删除确认',
    ],
    rowActions: ['下载', '删除', '复制路径'],
    emptyTitle: '暂无存储文件',
    emptyDescription: '连接 MinIO 后上传文件，后续知识库可以复用对象存储作为原始文件来源。',
  },
  {
    key: 'security',
    title: '安全中心',
    navTitle: '安全中心',
    href: '/security',
    description: '整合安全策略、数据权限、资源授权、高危审批、审计和运行监控。',
    permission: 'security:rule:view',
    status: 'ready',
    primaryAction: '查看安全态势',
    metrics: [
      { label: '安全评分', value: '100', helper: 'M38 总览' },
      { label: '待审批', value: '0', helper: '高危工具' },
      { label: '拒绝规则', value: '0', helper: '策略与 ACL' },
      { label: '安全事件', value: '0', helper: '最近 24h' },
    ],
    filters: ['安全模块', '风险等级', '策略关键词', '状态', '效果'],
    columns: ['模块', '状态', '关键指标', '风险信号', '入口'],
    detailSections: [
      '安全态势',
      '治理模块',
      '风险信号',
      '策略清单',
      '模拟评估',
      '评估日志',
      '审计与监控入口',
    ],
    rowActions: ['打开模块', '新建策略', '运行模拟', '查看审计', '处理审批'],
    emptyTitle: '暂无安全治理数据',
    emptyDescription: '配置安全策略、数据范围和资源授权后，安全中心会聚合展示治理状态。',
  },
  {
    key: 'tools',
    title: '工具中心',
    navTitle: '工具',
    href: '/tools',
    description: '管理 HTTP 工具、JSON Schema、鉴权配置、风险策略、测试和调用日志。',
    permission: 'tool:definition:view',
    status: 'ready',
    primaryAction: '新建 HTTP 工具',
    metrics: [
      { label: '工具', value: '0', helper: 'M07 数据源' },
      { label: '已启用', value: '0', helper: '可调用工具' },
      { label: '今日调用', value: '0', helper: '工具调用日志' },
      { label: '失败率', value: '0%', helper: '执行状态' },
    ],
    filters: ['关键词：名称/编码/链接', '类型', '状态', '风险等级'],
    columns: ['名称', '编码', '类型', '方法', '风险等级', '状态', '更新时间', '操作'],
    detailSections: [
      '基础信息',
      'HTTP 配置',
      '输入 JSON Schema',
      '输出 JSON Schema',
      '鉴权配置',
      '安全策略',
      '测试面板',
      '智能体绑定',
      '调用日志',
    ],
    rowActions: ['编辑', '复制', '启用', '停用', '测试', '删除', '详情'],
    emptyTitle: '暂无工具',
    emptyDescription: '创建 HTTP 工具，配置结构和鉴权后即可执行真实测试调用。',
  },
  {
    key: 'skills',
    title: '技能资产中心',
    navTitle: '技能资产',
    href: '/skills',
    description: '管理可复用业务 Skill、SOP 字段、版本发布和 Agent 引用关系。',
    permission: 'skill:hub:view',
    status: 'ready',
    primaryAction: '新建 Skill',
    metrics: [
      { label: 'Skill', value: '0', helper: 'M118 数据源' },
      { label: '已发布', value: '0', helper: '可绑定版本' },
      { label: '草稿', value: '0', helper: '待完善' },
      { label: 'Agent 引用', value: '0', helper: '绑定关系' },
    ],
    filters: ['关键词：名称/编码/描述', '分类', '状态', '负责人'],
    columns: ['名称', '编码', '分类', '状态', '版本', 'Agent 引用', '更新时间', '操作'],
    detailSections: [
      '基础信息',
      '触发场景',
      '输入要求',
      '执行步骤',
      '输出结构',
      '质量标准',
      '边界规则',
      '版本记录',
      'Agent 引用',
      '审计记录',
    ],
    rowActions: ['详情', '编辑', '复制', '发布', '删除'],
    emptyTitle: '暂无 Skill',
    emptyDescription: '创建可复用业务 Skill，并在详情页维护完整 SOP、版本记录和 Agent 引用。',
  },
  {
    key: 'conversations',
    title: '会话中心',
    navTitle: '会话',
    href: '/conversations',
    description: '查看智能体会话、消息、引用、工具调用、运行步骤和反馈。',
    permission: 'conversation:history:view',
    status: 'ready',
    primaryAction: '新建会话',
    metrics: [
      { label: '会话', value: '0', helper: 'M08 数据源' },
      { label: '消息', value: '0', helper: '已存储消息' },
      { label: '活跃运行', value: '0', helper: '运行时服务' },
      { label: '反馈', value: '0', helper: '用户评分' },
    ],
    filters: ['智能体', '用户', '状态', '最后消息时间'],
    columns: ['智能体', '用户', '标题', '消息', '状态', '最后消息时间', '操作'],
    detailSections: [
      '消息流',
      '引用',
      '工具调用',
      '运行步骤',
      '调试提示词',
      '模型配置',
      '反馈',
    ],
    rowActions: ['打开', '继续', '查看运行', '导出', '删除'],
    emptyTitle: '暂无会话',
    emptyDescription: '选择已发布智能体并发送首条消息，创建真实会话线程和运行记录。',
  },
  {
    key: 'approvals',
    title: '审批中心',
    navTitle: '审批',
    href: '/approvals',
    description: '集中处理高风险工具的待审批请求，追踪测试与运行时调用的审批决策。',
    permission: 'security:approval:view',
    status: 'ready',
    primaryAction: '处理审批',
    metrics: [
      { label: '待审批', value: '0', helper: 'M16 数据源' },
      { label: '已通过', value: '0', helper: '审批通过' },
      { label: '已拒绝', value: '0', helper: '审批拒绝' },
      { label: '运行时请求', value: '0', helper: '会话触发' },
    ],
    filters: ['关键词：工具/会话/申请人', '审批状态', '触发来源'],
    columns: ['时间', '工具', '来源', '审批状态', '执行状态', '申请人', '上下文'],
    detailSections: [
      '审批概览',
      '请求详情',
      '请求体',
      '响应体',
      '会话上下文',
      '审批动作',
    ],
    rowActions: ['查看详情', '批准执行', '拒绝请求'],
    emptyTitle: '暂无审批请求',
    emptyDescription: '高风险工具在测试或运行时触发后，会在这里等待人工审批。',
  },
  {
    key: 'approval_audits',
    title: '审批审计中心',
    navTitle: '审批审计',
    href: '/approval-audits',
    description: '全局检索工具审批和通知策略审批事件，按来源、状态、Trace 与关键词追踪审批链路。',
    permission: 'security:approval:view',
    status: 'ready',
    primaryAction: '检索审计事件',
    metrics: [
      { label: '审计事件', value: '0', helper: '统一审批事件' },
      { label: '成功事件', value: '0', helper: '批准或生效' },
      { label: '失败事件', value: '0', helper: '执行失败' },
      { label: 'Trace 覆盖', value: '0', helper: '链路追踪' },
    ],
    filters: ['关键词：标题/备注/Trace/请求 ID/操作人', '时间窗口', '审批来源', '事件类型', '事件状态'],
    columns: ['时间', '来源', '事件', '状态', '操作人', 'Trace ID', '请求 ID', '备注'],
    detailSections: [
      '审计概览',
      '来源分布',
      '事件类型排行',
      '事件列表',
      '事件详情',
      '事件元数据',
      '审批跳转',
      'Trace 跳转',
    ],
    rowActions: ['查看详情', '打开审批', '查看 Trace', '刷新数据', '清空筛选'],
    emptyTitle: '暂无审批审计事件',
    emptyDescription: '当工具审批或通知策略审批产生生命周期事件后，会在这里形成可检索审计台账。',
  },
  {
    key: 'monitor',
    title: '监控中心',
    navTitle: '监控',
    href: '/monitor',
    description: '运营平台健康、延迟、词元成本、模型/工具/检索增强指标和错误。',
    permission: 'monitor:log:view',
    status: 'ready',
    primaryAction: '导出报告',
    metrics: [
      { label: '今日调用', value: '0', helper: 'M09 数据源' },
      { label: '成功率', value: '0%', helper: '运行状态' },
      { label: '平均延迟', value: '0 ms', helper: '运行耗时' },
      { label: 'P95 延迟', value: '0 ms', helper: '链路指标' },
    ],
    filters: ['时间范围', '智能体', '模型', '状态'],
    columns: ['链路 ID', '模块', '状态', '延迟', '词元', '成本', '发生时间', '操作'],
    detailSections: [
      '调用概览',
      '词元成本趋势',
      '智能体排行',
      '模型监控',
      '工具监控',
      '检索增强监控',
      '错误详情',
    ],
    rowActions: ['查看链路', '打开运行', '复制链路 ID'],
    emptyTitle: '暂无监控数据',
    emptyDescription: '聚合运行、模型、工具和召回日志，形成可操作的监控视图。',
  },
  {
    key: 'billing',
    title: '成本与额度中心',
    navTitle: '成本额度',
    href: '/billing',
    description: '查看模型成本、接口密钥额度、成本趋势和用量风险。',
    permission: 'billing:center:view',
    status: 'ready',
    primaryAction: '刷新成本数据',
    metrics: [
      { label: '总成本', value: '$0.00', helper: '模型与步骤成本' },
      { label: '模型成本', value: '$0.00', helper: '模型调用' },
      { label: '词元', value: '0', helper: '模型与会话' },
      { label: '风险密钥', value: '0', helper: '额度预警' },
    ],
    filters: ['时间窗口', '风险等级', '供应商', '模型', '接口密钥'],
    columns: ['供应商', '模型', '调用', '词元', '成本', '平均延迟', '成功率'],
    detailSections: [
      '成本趋势',
      '供应商成本',
      '模型成本排行',
      '接口密钥额度',
      '额度风险',
      '会话步骤成本',
    ],
    rowActions: ['刷新', '查看详情'],
    emptyTitle: '暂无成本数据',
    emptyDescription: '当前租户尚未产生可统计的模型调用或会话步骤成本。',
  },
  {
    key: 'api_keys',
    title: 'API Key 管理中心',
    navTitle: 'API Key',
    href: '/api-keys',
    description: '管理外部系统调用 Agent 的机器密钥、调用范围、Agent 白名单、限流、额度和 IP 白名单。',
    permission: 'system:api_key:view',
    status: 'ready',
    primaryAction: '创建密钥',
    metrics: [
      { label: '接口密钥', value: '0', helper: '租户外部凭证' },
      { label: '启用密钥', value: '0', helper: '可调用 Agent' },
      { label: '额度风险', value: '0', helper: '日额度预警' },
      { label: '流式权限', value: '0', helper: '外部 SSE' },
    ],
    filters: ['关键词：名称/密钥/Agent', '状态', '额度风险'],
    columns: ['名称', '脱敏密钥', '状态', '调用范围', 'Agent 白名单', '限流', '额度', '最近使用', '操作'],
    detailSections: [
      '外部调用地址',
      '请求头说明',
      '创建密钥表单',
      '一次性明文密钥',
      '密钥清单',
      '额度风险',
      'IP 白名单',
      '治理提示',
    ],
    rowActions: ['复制地址', '创建密钥', '复制新密钥', '删除密钥', '刷新'],
    emptyTitle: '暂无接口密钥',
    emptyDescription: '创建受限 API Key 后，外部服务可以通过授权范围调用指定 Agent。',
  },
  {
    key: 'api_reference',
    title: '开放接口文档中心',
    navTitle: '接口文档',
    href: '/api-reference',
    description: '查看外部 Agent 调用接口、鉴权方式、请求响应结构、错误码和安全校验链路。',
    permission: 'system:api_key:view',
    status: 'ready',
    primaryAction: '复制接口',
    metrics: [
      { label: '开放接口', value: '1', helper: '外部 Agent 调用' },
      { label: '鉴权方式', value: '2', helper: 'Bearer / x-api-key' },
      { label: '请求字段', value: '2', helper: 'message + title' },
      { label: '安全校验', value: '8', helper: '权限与审计闭环' },
    ],
    filters: ['接口路径', '鉴权方式', '请求字段', '响应字段', '错误码'],
    columns: ['接口', '方法', '鉴权', '权限', '请求体', '响应', '错误处理'],
    detailSections: [
      '接口入口',
      '鉴权方式',
      '快速接入流程',
      '请求体字段',
      '响应字段',
      'curl 示例',
      'TypeScript 示例',
      '安全校验链路',
      '常见错误',
    ],
    rowActions: ['复制接口', '复制 curl', '复制 TypeScript', '打开 API Key', '打开 Swagger'],
    emptyTitle: '暂无开放接口',
    emptyDescription: '当前版本开放外部 Agent 非流式调用，后续流式接口会在这里补充。',
  },
  {
    key: 'audit',
    title: '审计中心',
    navTitle: '审计',
    href: '/audit',
    description: '查询登录日志、操作日志、安全事件和配置变更记录。',
    permission: 'security:audit:view',
    status: 'ready',
    primaryAction: '导出审计',
    metrics: [
      { label: '登录日志', value: '0', helper: 'M02/M09 数据源' },
      { label: '操作', value: '0', helper: '写入审计记录' },
      { label: '安全事件', value: '0', helper: '安全策略' },
      { label: '配置变更', value: '0', helper: '差异记录' },
    ],
    filters: ['用户', '租户', '模块', '动作', '时间范围', '结果'],
    columns: ['时间', '用户', '租户', '模块', '动作', '结果', '链路 ID', '操作'],
    detailSections: [
      '请求摘要',
      '响应摘要',
      'IP 地址',
      '客户端标识',
      '链路 ID',
      '前后差异',
    ],
    rowActions: ['详情', '复制链路 ID'],
    emptyTitle: '暂无审计记录',
    emptyDescription: '统一查看登录日志、操作日志、安全失败和配置变更详情。',
  },
  {
    key: 'departments',
    title: '部门组织架构中心',
    navTitle: '部门',
    href: '/departments',
    description: '管理租户部门树、负责人、成员归属和组织属性，为 ABAC 与资源授权提供部门边界。',
    permission: 'system:department:view',
    status: 'ready',
    primaryAction: '新建部门',
    metrics: [
      { label: '部门', value: '0', helper: '租户组织树' },
      { label: '启用部门', value: '0', helper: 'ACTIVE' },
      { label: '成员', value: '0', helper: '已归属用户' },
      { label: '根部门', value: '0', helper: '一级组织' },
    ],
    filters: ['关键词：名称/编码/描述', '状态', '父级部门'],
    columns: ['名称', '编码', '负责人', '成员', '状态', '排序', '更新时间', '操作'],
    detailSections: [
      '组织树',
      '部门清单',
      '部门详情',
      '成员列表',
      '新建与编辑',
      '启用停用',
      '删除确认',
      'ABAC 属性提示',
    ],
    rowActions: ['新建子部门', '编辑', '启用', '停用', '删除'],
    emptyTitle: '暂无部门',
    emptyDescription: '创建总部或业务部门后，可以把用户归属到部门，并用于后续数据权限策略。',
  },
  {
    key: 'tenants',
    title: '租户管理中心',
    navTitle: '租户',
    href: '/tenants',
    description: '查看并维护当前租户资料、启停状态和租户上下文治理边界。',
    permission: 'system:tenant:view',
    status: 'ready',
    primaryAction: '编辑租户',
    metrics: [
      { label: '租户范围', value: '1', helper: '当前上下文' },
      { label: '租户状态', value: '启用', helper: 'ACTIVE' },
      { label: '租户编码', value: '-', helper: '唯一标识' },
      { label: '更新时间', value: '-', helper: '最近变更' },
    ],
    filters: ['关键词：名称/编码', '状态'],
    columns: ['租户名称', '编码', '状态', '创建时间', '更新时间', '操作'],
    detailSections: [
      '当前租户资料',
      '租户列表',
      '状态治理',
      '编辑租户',
      '租户隔离说明',
      '后续 SaaS 边界',
    ],
    rowActions: ['编辑', '刷新'],
    emptyTitle: '暂无租户数据',
    emptyDescription: '当前接口按租户上下文隔离，列表通常只返回当前租户。',
  },
  {
    key: 'users',
    title: '用户管理中心',
    navTitle: '用户',
    href: '/users',
    description: '管理租户用户账号、部门归属、角色分配和启停状态。',
    permission: 'system:user:view',
    status: 'ready',
    primaryAction: '新建用户',
    metrics: [
      { label: '用户总数', value: '0', helper: '租户账号' },
      { label: '启用用户', value: '0', helper: '可登录' },
      { label: '部门归属', value: '0', helper: 'ABAC 属性' },
      { label: '角色绑定', value: '0', helper: 'RBAC' },
    ],
    filters: ['关键词：名称/邮箱', '状态', '部门'],
    columns: ['名称', '邮箱', '部门', '状态', '角色', '最近登录', '更新时间', '操作'],
    detailSections: [
      '用户清单',
      '用户详情',
      '新建用户',
      '编辑用户',
      '部门归属',
      '角色绑定',
      '删除确认',
    ],
    rowActions: ['详情', '编辑', '删除', '刷新'],
    emptyTitle: '暂无用户',
    emptyDescription: '创建租户用户后，可以分配部门和角色，用于后续权限与资源授权。',
  },
  {
    key: 'roles',
    title: '角色权限中心',
    navTitle: '角色',
    href: '/roles',
    description: '管理租户角色、权限编码授权、用户引用和菜单授权摘要，形成 RBAC 权限闭环。',
    permission: 'system:role:view',
    status: 'ready',
    primaryAction: '新建角色',
    metrics: [
      { label: '角色', value: '0', helper: '租户角色目录' },
      { label: '启用角色', value: '0', helper: 'ACTIVE' },
      { label: '用户绑定', value: '0', helper: '用户角色关系' },
      { label: '权限绑定', value: '0', helper: '接口权限矩阵' },
    ],
    filters: ['关键词：名称/编码/描述', '状态'],
    columns: ['角色', '状态', '类型', '用户', '权限', '菜单', '更新时间', '操作'],
    detailSections: [
      '角色目录',
      '角色详情',
      '权限编码矩阵',
      '用户引用',
      '菜单引用',
      '新建与编辑',
      '启用停用',
      '删除确认',
    ],
    rowActions: ['编辑', '启用', '停用', '删除', '保存权限'],
    emptyTitle: '暂无角色',
    emptyDescription: '创建自定义角色并分配权限编码后，可以在用户管理中绑定角色。',
  },
  {
    key: 'menus',
    title: '菜单中心',
    navTitle: '菜单',
    href: '/menus',
    description: '管理租户菜单树、页面入口、按钮节点和角色菜单授权。',
    permission: 'system:menu:view',
    status: 'ready',
    primaryAction: '新建菜单',
    metrics: [
      { label: '菜单节点', value: '0', helper: '租户菜单树' },
      { label: '页面菜单', value: '0', helper: '可进入页面' },
      { label: '按钮权限', value: '0', helper: '操作入口' },
      { label: '角色授权', value: '0', helper: 'RBAC 菜单绑定' },
    ],
    filters: ['关键词：名称/编码/路径/权限', '类型', '状态', '可见性'],
    columns: ['名称', '编码', '类型', '路径', '权限编码', '状态', '可见', '角色', '操作'],
    detailSections: [
      '菜单树',
      '节点详情',
      '新建与编辑',
      '启用停用',
      '角色菜单授权',
      '动态导航预览',
      '删除确认',
    ],
    rowActions: ['编辑', '启用', '停用', '删除', '角色授权'],
    emptyTitle: '暂无菜单节点',
    emptyDescription: '创建目录、页面和按钮节点后，角色授权会决定用户能看到哪些入口。',
  },
  {
    key: 'data_scopes',
    title: '数据权限中心',
    navTitle: '数据权限',
    href: '/data-scopes',
    description: '按角色配置 Agent、知识库、工具、模型、会话和审计等资源的数据访问范围。',
    permission: 'system:data_scope:view',
    status: 'ready',
    primaryAction: '保存数据范围',
    metrics: [
      { label: '已配置角色', value: '0', helper: '角色覆盖' },
      { label: '数据范围', value: '0', helper: '资源矩阵' },
      { label: '全部范围', value: '0', helper: 'ALL' },
      { label: '自定义范围', value: '0', helper: 'CUSTOM' },
    ],
    filters: ['角色关键词', '角色状态', '资源类型', '范围类型'],
    columns: ['资源类型', '数据范围', '部门', '用户', '资源', '更新时间', '操作'],
    detailSections: [
      '角色目录',
      '资源范围矩阵',
      '范围类型配置',
      '自定义部门',
      '自定义用户',
      '资源 ID 清单',
      '生效预览',
      '保存确认',
    ],
    rowActions: ['选择资源', '预览', '保存', '重置'],
    emptyTitle: '暂无数据权限',
    emptyDescription: '选择角色后，可以为不同资源类型配置租户、部门、本人或自定义数据范围。',
  },
  {
    key: 'resource_acls',
    title: '资源授权中心',
    navTitle: '资源授权',
    href: '/resource-acls',
    description: '按具体资源对象授权给用户、角色、部门或租户主体，形成对象级 Resource ACL。',
    permission: 'system:resource_acl:view',
    status: 'ready',
    primaryAction: '新建授权',
    metrics: [
      { label: '授权规则', value: '0', helper: 'Resource ACL' },
      { label: '启用规则', value: '0', helper: 'ACTIVE' },
      { label: '允许规则', value: '0', helper: 'ALLOW' },
      { label: '拒绝规则', value: '0', helper: 'DENY 优先' },
    ],
    filters: ['资源类型', '主体类型', '授权效果', '状态', '资源/主体关键词'],
    columns: ['资源', '主体', '权限编码', '效果', '状态', '条件', '更新时间', '操作'],
    detailSections: [
      '资源选择',
      '主体选择',
      '权限编码',
      '允许/拒绝',
      '条件 JSON',
      '规则列表',
      '模拟检查',
      '删除确认',
    ],
    rowActions: ['新建授权', '编辑', '删除', '模拟检查'],
    emptyTitle: '暂无资源授权',
    emptyDescription: '选择具体资源和主体后，可以创建允许或拒绝的对象级授权规则。',
  },
  {
    key: 'settings',
    title: '系统设置',
    navTitle: '系统设置',
    href: '/settings',
    description: '集中维护系统参数，并提供租户、用户、角色、API Key、安全策略和文件存储配置入口。',
    permission: 'system:settings:view',
    status: 'ready',
    primaryAction: '打开系统设置',
    metrics: [
      { label: '系统参数', value: '0', helper: '租户级配置' },
      { label: '启用参数', value: '0', helper: '当前有效' },
      { label: '敏感参数', value: '0', helper: '脱敏展示' },
      { label: '配置入口', value: '6', helper: '专项页面' },
    ],
    filters: ['参数分类', '参数状态'],
    columns: ['参数名称', '参数 Key', '分类', '类型', '状态', '更新时间', '操作'],
    detailSections: [
      '系统参数概览',
      '配置入口',
      '参数分类筛选',
      '参数编辑',
      '恢复默认',
      '通知策略影响预览',
      '通知策略审计',
      '版本快照回滚',
    ],
    rowActions: ['打开入口', '保存参数', '恢复默认', '预览影响', '回滚快照'],
    emptyTitle: '暂无系统参数',
    emptyDescription: '系统参数由控制接口提供；租户、用户、角色和 API Key 等管理能力请从配置入口进入专项页面。',
  },
];

export function getModuleSpec(key: string) {
  return moduleSpecs.find((moduleSpec) => moduleSpec.key === key);
}

export function requireModuleSpec(key: string) {
  const moduleSpec = getModuleSpec(key);

  if (!moduleSpec) {
    throw new Error(`Unknown module spec: ${key}`);
  }

  return moduleSpec;
}
