export type ModuleStatus = 'ready' | 'planned' | 'mock';

export interface MetricPreview {
  label: string;
  value: string;
  helper: string;
}

export interface ModuleSpec {
  key: string;
  title: string;
  navTitle: string;
  href: string;
  description: string;
  permission: string;
  status: ModuleStatus;
  primaryAction: string;
  metrics: MetricPreview[];
  filters: string[];
  columns: string[];
  detailSections: string[];
  rowActions: string[];
  emptyTitle: string;
  emptyDescription: string;
}

export const moduleSpecs: ModuleSpec[] = [
  {
    key: 'agents',
    title: '智能体配置中心',
    navTitle: '智能体',
    href: '/agents',
    description: '创建、配置、测试、版本化、发布、停用、复制并审计企业智能体。',
    permission: 'agent:agent:view',
    status: 'ready',
    primaryAction: '新建智能体',
    metrics: [
      { label: '智能体', value: '0', helper: 'M03 数据源' },
      { label: '已发布', value: '0', helper: '发布状态' },
      { label: '草稿', value: '0', helper: '草稿状态' },
      { label: '已停用', value: '0', helper: '停用状态' },
    ],
    filters: ['关键词：名称/编码/描述', '状态', '分类', '负责人'],
    columns: ['名称', '编码', '状态', '版本', '默认模型', '更新时间', '负责人', '操作'],
    detailSections: [
      '基础信息',
      '运行配置',
      '模型绑定',
      '提示词绑定',
      '知识库绑定',
      '工具绑定',
      '版本',
      '会话测试',
      '审计记录',
    ],
    rowActions: ['编辑', '复制', '启用', '停用', '删除', '详情'],
    emptyTitle: '暂无智能体',
    emptyDescription: '创建智能体，并基于控制接口数据表管理版本化发布流程。',
  },
  {
    key: 'prompts',
    title: '提示词中心',
    navTitle: '提示词',
    href: '/prompts',
    description: '管理提示词模板、变量、版本、测试、回滚和智能体引用。',
    permission: 'prompt:template:view',
    status: 'ready',
    primaryAction: '新建提示词',
    metrics: [
      { label: '模板', value: '0', helper: 'M05 数据源' },
      { label: '已发布', value: '0', helper: '不可变版本' },
      { label: '草稿', value: '0', helper: '可编辑状态' },
      { label: '测试', value: '0', helper: '提示词测试记录' },
    ],
    filters: ['关键词：名称/编码/内容', '类型', '状态', '创建人'],
    columns: ['名称', '编码', '类型', '状态', '版本', '更新时间', '操作'],
    detailSections: [
      '基础信息',
      '提示词编辑器',
      '变量',
      '版本',
      '测试面板',
      '智能体引用',
      '审计记录',
    ],
    rowActions: ['编辑', '复制', '发布', '回滚', '删除', '测试'],
    emptyTitle: '暂无提示词模板',
    emptyDescription: '创建提示词模板、变量、不可变版本、渲染检查和智能体引用。',
  },
  {
    key: 'models',
    title: '模型中心',
    navTitle: '模型',
    href: '/models',
    description: '管理供应商、模型配置、加密接口密钥、成本、限流和调用日志。',
    permission: 'model:config:view',
    status: 'ready',
    primaryAction: '新建供应商',
    metrics: [
      { label: '供应商', value: '0', helper: 'M04 数据源' },
      { label: '启用模型', value: '0', helper: '可绑定' },
      { label: '今日调用', value: '0', helper: '模型调用日志' },
      { label: '今日成本', value: '$0.00', helper: '成本规则' },
    ],
    filters: ['关键词：供应商/模型', '供应商类型', '能力', '状态'],
    columns: ['供应商', '模型', '能力', '上下文', '输入价格', '输出价格', '限流', '状态'],
    detailSections: [
      '供应商资料',
      '脱敏接口密钥',
      '能力',
      '成本规则',
      '限流',
      '调用测试面板',
      '调用日志',
    ],
    rowActions: ['编辑', '停用', '删除', '测试', '详情'],
    emptyTitle: '暂无模型供应商',
    emptyDescription: '配置 OpenAI 兼容供应商、脱敏接口密钥、模型、价格和调用测试。',
  },
  {
    key: 'knowledge',
    title: '知识库中心',
    navTitle: '知识库',
    href: '/knowledge',
    description: '管理知识库、文档、切片、处理任务、检索测试和智能体绑定。',
    permission: 'knowledge:base:view',
    status: 'ready',
    primaryAction: '新建知识库',
    metrics: [
      { label: '知识库', value: '0', helper: 'M06 数据源' },
      { label: '文档', value: '0', helper: 'PostgreSQL 元数据' },
      { label: '切片', value: '0', helper: 'PostgreSQL 切片' },
      { label: '失败任务', value: '0', helper: '处理任务' },
    ],
    filters: ['关键词：名称/编码/描述', '状态', '可见范围', '更新时间'],
    columns: ['名称', '编码', '文档', '切片', '状态', '更新时间', '操作'],
    detailSections: [
      '基础信息',
      '文档列表',
      '上传面板',
      '文档预览',
      '切片',
      '检索测试',
      '处理任务',
      '智能体绑定',
    ],
    rowActions: ['编辑', '上传', '检索测试', '重建索引', '删除', '详情'],
    emptyTitle: '暂无知识库',
    emptyDescription: '上传文本或 Markdown 文档内容，生成切片、重建索引并运行检索测试。',
  },
  {
    key: 'storage',
    title: '文件存储中心',
    navTitle: '文件存储',
    href: '/storage',
    description: '管理 MinIO 存储设置、桶初始化、租户文件上传、下载和删除。',
    permission: 'storage:object:view',
    status: 'ready',
    primaryAction: '上传文件',
    metrics: [
      { label: '对象', value: '0', helper: 'MinIO 对象' },
      { label: '容量', value: '0 B', helper: '租户前缀' },
      { label: '桶状态', value: '未检查', helper: 'aiaget-files' },
      { label: '连接', value: '未知', helper: 'MinIO' },
    ],
    filters: ['关键词：文件名/路径', '目录前缀', '更新时间'],
    columns: ['文件名', '目录', '大小', 'ETag', '更新时间', '操作'],
    detailSections: [
      '存储设置',
      '连接状态',
      '桶初始化',
      '上传文件',
      '文件列表',
      '下载链接',
      '删除确认',
    ],
    rowActions: ['下载', '删除', '复制路径'],
    emptyTitle: '暂无存储文件',
    emptyDescription: '连接 MinIO 后上传文件，后续知识库可以复用对象存储作为原始文件来源。',
  },
  {
    key: 'security',
    title: '安全中心',
    navTitle: '安全中心',
    href: '/security',
    description: '整合安全策略、数据权限、资源授权、高危审批、审计和运行监控。',
    permission: 'security:rule:view',
    status: 'ready',
    primaryAction: '查看安全态势',
    metrics: [
      { label: '安全评分', value: '100', helper: 'M38 总览' },
      { label: '待审批', value: '0', helper: '高危工具' },
      { label: '拒绝规则', value: '0', helper: '策略与 ACL' },
      { label: '安全事件', value: '0', helper: '最近 24h' },
    ],
    filters: ['安全模块', '风险等级', '策略关键词', '状态', '效果'],
    columns: ['模块', '状态', '关键指标', '风险信号', '入口'],
    detailSections: [
      '安全态势',
      '治理模块',
      '风险信号',
      '策略清单',
      '模拟评估',
      '评估日志',
      '审计与监控入口',
    ],
    rowActions: ['打开模块', '新建策略', '运行模拟', '查看审计', '处理审批'],
    emptyTitle: '暂无安全治理数据',
    emptyDescription: '配置安全策略、数据范围和资源授权后，安全中心会聚合展示治理状态。',
  },
  {
    key: 'tools',
    title: '工具中心',
    navTitle: '工具',
    href: '/tools',
    description: '管理 HTTP 工具、JSON Schema、鉴权配置、风险策略、测试和调用日志。',
    permission: 'tool:definition:view',
    status: 'ready',
    primaryAction: '新建 HTTP 工具',
    metrics: [
      { label: '工具', value: '0', helper: 'M07 数据源' },
      { label: '已启用', value: '0', helper: '可调用工具' },
      { label: '今日调用', value: '0', helper: '工具调用日志' },
      { label: '失败率', value: '0%', helper: '执行状态' },
    ],
    filters: ['关键词：名称/编码/链接', '类型', '状态', '风险等级'],
    columns: ['名称', '编码', '类型', '方法', '风险等级', '状态', '更新时间', '操作'],
    detailSections: [
      '基础信息',
      'HTTP 配置',
      '输入 JSON Schema',
      '输出 JSON Schema',
      '鉴权配置',
      '安全策略',
      '测试面板',
      '智能体绑定',
      '调用日志',
    ],
    rowActions: ['编辑', '复制', '启用', '停用', '测试', '删除', '详情'],
    emptyTitle: '暂无工具',
    emptyDescription: '创建 HTTP 工具，配置结构和鉴权后即可执行真实测试调用。',
  },
  {
    key: 'conversations',
    title: '会话中心',
    navTitle: '会话',
    href: '/conversations',
    description: '查看智能体会话、消息、引用、工具调用、运行步骤和反馈。',
    permission: 'conversation:history:view',
    status: 'ready',
    primaryAction: '新建会话',
    metrics: [
      { label: '会话', value: '0', helper: 'M08 数据源' },
      { label: '消息', value: '0', helper: '已存储消息' },
      { label: '活跃运行', value: '0', helper: '运行时服务' },
      { label: '反馈', value: '0', helper: '用户评分' },
    ],
    filters: ['智能体', '用户', '状态', '最后消息时间'],
    columns: ['智能体', '用户', '标题', '消息', '状态', '最后消息时间', '操作'],
    detailSections: [
      '消息流',
      '引用',
      '工具调用',
      '运行步骤',
      '调试提示词',
      '模型配置',
      '反馈',
    ],
    rowActions: ['打开', '继续', '查看运行', '导出', '删除'],
    emptyTitle: '暂无会话',
    emptyDescription: '选择已发布智能体并发送首条消息，创建真实会话线程和运行记录。',
  },
  {
    key: 'approvals',
    title: '审批中心',
    navTitle: '审批',
    href: '/approvals',
    description: '集中处理高风险工具的待审批请求，追踪测试与运行时调用的审批决策。',
    permission: 'security:approval:view',
    status: 'ready',
    primaryAction: '处理审批',
    metrics: [
      { label: '待审批', value: '0', helper: 'M16 数据源' },
      { label: '已通过', value: '0', helper: '审批通过' },
      { label: '已拒绝', value: '0', helper: '审批拒绝' },
      { label: '运行时请求', value: '0', helper: '会话触发' },
    ],
    filters: ['关键词：工具/会话/申请人', '审批状态', '触发来源'],
    columns: ['时间', '工具', '来源', '审批状态', '执行状态', '申请人', '上下文'],
    detailSections: [
      '审批概览',
      '请求详情',
      '请求体',
      '响应体',
      '会话上下文',
      '审批动作',
    ],
    rowActions: ['查看详情', '批准执行', '拒绝请求'],
    emptyTitle: '暂无审批请求',
    emptyDescription: '高风险工具在测试或运行时触发后，会在这里等待人工审批。',
  },
  {
    key: 'monitor',
    title: '监控中心',
    navTitle: '监控',
    href: '/monitor',
    description: '运营平台健康、延迟、词元成本、模型/工具/检索增强指标和错误。',
    permission: 'monitor:log:view',
    status: 'ready',
    primaryAction: '导出报告',
    metrics: [
      { label: '今日调用', value: '0', helper: 'M09 数据源' },
      { label: '成功率', value: '0%', helper: '运行状态' },
      { label: '平均延迟', value: '0 ms', helper: '运行耗时' },
      { label: 'P95 延迟', value: '0 ms', helper: '链路指标' },
    ],
    filters: ['时间范围', '智能体', '模型', '状态'],
    columns: ['链路 ID', '模块', '状态', '延迟', '词元', '成本', '发生时间', '操作'],
    detailSections: [
      '调用概览',
      '词元成本趋势',
      '智能体排行',
      '模型监控',
      '工具监控',
      '检索增强监控',
      '错误详情',
    ],
    rowActions: ['查看链路', '打开运行', '复制链路 ID'],
    emptyTitle: '暂无监控数据',
    emptyDescription: '聚合运行、模型、工具和召回日志，形成可操作的监控视图。',
  },
  {
    key: 'billing',
    title: '成本与额度中心',
    navTitle: '成本额度',
    href: '/billing',
    description: '查看模型成本、接口密钥额度、成本趋势和用量风险。',
    permission: 'monitor:log:view',
    status: 'ready',
    primaryAction: '刷新成本数据',
    metrics: [
      { label: '总成本', value: '$0.00', helper: '模型与步骤成本' },
      { label: '模型成本', value: '$0.00', helper: '模型调用' },
      { label: '词元', value: '0', helper: '模型与会话' },
      { label: '风险密钥', value: '0', helper: '额度预警' },
    ],
    filters: ['时间窗口', '风险等级', '供应商', '模型', '接口密钥'],
    columns: ['供应商', '模型', '调用', '词元', '成本', '平均延迟', '成功率'],
    detailSections: [
      '成本趋势',
      '供应商成本',
      '模型成本排行',
      '接口密钥额度',
      '额度风险',
      '会话步骤成本',
    ],
    rowActions: ['刷新', '查看详情'],
    emptyTitle: '暂无成本数据',
    emptyDescription: '当前租户尚未产生可统计的模型调用或会话步骤成本。',
  },
  {
    key: 'audit',
    title: '审计中心',
    navTitle: '审计',
    href: '/audit',
    description: '查询登录日志、操作日志、安全事件和配置变更记录。',
    permission: 'security:audit:view',
    status: 'ready',
    primaryAction: '导出审计',
    metrics: [
      { label: '登录日志', value: '0', helper: 'M02/M09 数据源' },
      { label: '操作', value: '0', helper: '写入审计记录' },
      { label: '安全事件', value: '0', helper: '安全策略' },
      { label: '配置变更', value: '0', helper: '差异记录' },
    ],
    filters: ['用户', '租户', '模块', '动作', '时间范围', '结果'],
    columns: ['时间', '用户', '租户', '模块', '动作', '结果', '链路 ID', '操作'],
    detailSections: [
      '请求摘要',
      '响应摘要',
      'IP 地址',
      '客户端标识',
      '链路 ID',
      '前后差异',
    ],
    rowActions: ['详情', '复制链路 ID'],
    emptyTitle: '暂无审计记录',
    emptyDescription: '统一查看登录日志、操作日志、安全失败和配置变更详情。',
  },
  {
    key: 'departments',
    title: '部门组织架构中心',
    navTitle: '部门',
    href: '/departments',
    description: '管理租户部门树、负责人、成员归属和组织属性，为 ABAC 与资源授权提供部门边界。',
    permission: 'system:department:view',
    status: 'ready',
    primaryAction: '新建部门',
    metrics: [
      { label: '部门', value: '0', helper: '租户组织树' },
      { label: '启用部门', value: '0', helper: 'ACTIVE' },
      { label: '成员', value: '0', helper: '已归属用户' },
      { label: '根部门', value: '0', helper: '一级组织' },
    ],
    filters: ['关键词：名称/编码/描述', '状态', '父级部门'],
    columns: ['名称', '编码', '负责人', '成员', '状态', '排序', '更新时间', '操作'],
    detailSections: [
      '组织树',
      '部门清单',
      '部门详情',
      '成员列表',
      '新建与编辑',
      '启用停用',
      '删除确认',
      'ABAC 属性提示',
    ],
    rowActions: ['新建子部门', '编辑', '启用', '停用', '删除'],
    emptyTitle: '暂无部门',
    emptyDescription: '创建总部或业务部门后，可以把用户归属到部门，并用于后续数据权限策略。',
  },
  {
    key: 'roles',
    title: '角色权限中心',
    navTitle: '角色',
    href: '/roles',
    description: '管理租户角色、权限编码授权、用户引用和菜单授权摘要，形成 RBAC 权限闭环。',
    permission: 'system:role:view',
    status: 'ready',
    primaryAction: '新建角色',
    metrics: [
      { label: '角色', value: '0', helper: '租户角色目录' },
      { label: '启用角色', value: '0', helper: 'ACTIVE' },
      { label: '用户绑定', value: '0', helper: '用户角色关系' },
      { label: '权限绑定', value: '0', helper: '接口权限矩阵' },
    ],
    filters: ['关键词：名称/编码/描述', '状态'],
    columns: ['角色', '状态', '类型', '用户', '权限', '菜单', '更新时间', '操作'],
    detailSections: [
      '角色目录',
      '角色详情',
      '权限编码矩阵',
      '用户引用',
      '菜单引用',
      '新建与编辑',
      '启用停用',
      '删除确认',
    ],
    rowActions: ['编辑', '启用', '停用', '删除', '保存权限'],
    emptyTitle: '暂无角色',
    emptyDescription: '创建自定义角色并分配权限编码后，可以在用户管理中绑定角色。',
  },
  {
    key: 'menus',
    title: '菜单中心',
    navTitle: '菜单',
    href: '/menus',
    description: '管理租户菜单树、页面入口、按钮节点和角色菜单授权。',
    permission: 'system:menu:view',
    status: 'ready',
    primaryAction: '新建菜单',
    metrics: [
      { label: '菜单节点', value: '0', helper: '租户菜单树' },
      { label: '页面菜单', value: '0', helper: '可进入页面' },
      { label: '按钮权限', value: '0', helper: '操作入口' },
      { label: '角色授权', value: '0', helper: 'RBAC 菜单绑定' },
    ],
    filters: ['关键词：名称/编码/路径/权限', '类型', '状态', '可见性'],
    columns: ['名称', '编码', '类型', '路径', '权限编码', '状态', '可见', '角色', '操作'],
    detailSections: [
      '菜单树',
      '节点详情',
      '新建与编辑',
      '启用停用',
      '角色菜单授权',
      '动态导航预览',
      '删除确认',
    ],
    rowActions: ['编辑', '启用', '停用', '删除', '角色授权'],
    emptyTitle: '暂无菜单节点',
    emptyDescription: '创建目录、页面和按钮节点后，角色授权会决定用户能看到哪些入口。',
  },
  {
    key: 'data_scopes',
    title: '数据权限中心',
    navTitle: '数据权限',
    href: '/data-scopes',
    description: '按角色配置 Agent、知识库、工具、模型、会话和审计等资源的数据访问范围。',
    permission: 'system:data_scope:view',
    status: 'ready',
    primaryAction: '保存数据范围',
    metrics: [
      { label: '已配置角色', value: '0', helper: '角色覆盖' },
      { label: '数据范围', value: '0', helper: '资源矩阵' },
      { label: '全部范围', value: '0', helper: 'ALL' },
      { label: '自定义范围', value: '0', helper: 'CUSTOM' },
    ],
    filters: ['角色关键词', '角色状态', '资源类型', '范围类型'],
    columns: ['资源类型', '数据范围', '部门', '用户', '资源', '更新时间', '操作'],
    detailSections: [
      '角色目录',
      '资源范围矩阵',
      '范围类型配置',
      '自定义部门',
      '自定义用户',
      '资源 ID 清单',
      '生效预览',
      '保存确认',
    ],
    rowActions: ['选择资源', '预览', '保存', '重置'],
    emptyTitle: '暂无数据权限',
    emptyDescription: '选择角色后，可以为不同资源类型配置租户、部门、本人或自定义数据范围。',
  },
  {
    key: 'resource_acls',
    title: '资源授权中心',
    navTitle: '资源授权',
    href: '/resource-acls',
    description: '按具体资源对象授权给用户、角色、部门或租户主体，形成对象级 Resource ACL。',
    permission: 'system:resource_acl:view',
    status: 'ready',
    primaryAction: '新建授权',
    metrics: [
      { label: '授权规则', value: '0', helper: 'Resource ACL' },
      { label: '启用规则', value: '0', helper: 'ACTIVE' },
      { label: '允许规则', value: '0', helper: 'ALLOW' },
      { label: '拒绝规则', value: '0', helper: 'DENY 优先' },
    ],
    filters: ['资源类型', '主体类型', '授权效果', '状态', '资源/主体关键词'],
    columns: ['资源', '主体', '权限编码', '效果', '状态', '条件', '更新时间', '操作'],
    detailSections: [
      '资源选择',
      '主体选择',
      '权限编码',
      '允许/拒绝',
      '条件 JSON',
      '规则列表',
      '模拟检查',
      '删除确认',
    ],
    rowActions: ['新建授权', '编辑', '删除', '模拟检查'],
    emptyTitle: '暂无资源授权',
    emptyDescription: '选择具体资源和主体后，可以创建允许或拒绝的对象级授权规则。',
  },
  {
    key: 'settings',
    title: '设置中心',
    navTitle: '设置',
    href: '/settings',
    description: '准备租户、用户、角色、接口密钥、安全、环境和部署设置。',
    permission: 'system:settings:view',
    status: 'ready',
    primaryAction: '打开租户设置',
    metrics: [
      { label: '租户', value: '1', helper: '演示会话' },
      { label: '用户', value: '1', helper: 'M02 数据源' },
      { label: '角色', value: '0', helper: '权限控制设置' },
      { label: '接口密钥', value: '0', helper: '机器调用' },
    ],
    filters: ['设置分类', '状态', '更新人'],
    columns: ['分类', '名称', '状态', '更新人', '更新时间', '操作'],
    detailSections: [
      '租户资料',
      '用户与角色设置',
      '接口密钥设置',
      '安全策略',
      'CORS 白名单',
      '环境变量',
    ],
    rowActions: ['打开', '编辑', '审计'],
    emptyTitle: '设置暂未接入',
    emptyDescription: '管理当前租户资料、用户、角色与接口密钥，维持租户级访问和安全边界。',
  },
];

export function getModuleSpec(key: string) {
  return moduleSpecs.find((moduleSpec) => moduleSpec.key === key);
}

export function requireModuleSpec(key: string) {
  const moduleSpec = getModuleSpec(key);

  if (!moduleSpec) {
    throw new Error(`Unknown module spec: ${key}`);
  }

  return moduleSpec;
}
