DO $$
DECLARE
  table_record RECORD;
  column_record RECORD;
  comment_text TEXT;
BEGIN
  FOR table_record IN
    SELECT table_name
    FROM information_schema.tables
    WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
  LOOP
    comment_text := CASE table_record.table_name
      WHEN '_prisma_migrations' THEN 'Prisma 迁移历史表。'
      WHEN 'tenant' THEN '租户主表。'
      WHEN 'user' THEN '用户主表。'
      WHEN 'department' THEN '部门组织架构表，用于维护租户内部门树、负责人和成员归属。'
      WHEN 'role' THEN '角色定义表。'
      WHEN 'permission' THEN '权限定义表。'
      WHEN 'user_role' THEN '用户与角色关联表。'
      WHEN 'role_permission' THEN '角色与权限关联表。'
      WHEN 'menu' THEN '控制台菜单表，用于配置目录、页面和按钮节点。'
      WHEN 'role_menu' THEN '角色与菜单关联表，用于控制角色可见菜单和按钮。'
      WHEN 'role_data_scope' THEN '角色数据权限范围表，用于按角色和资源类型配置 ALL、TENANT、DEPT、DEPT_AND_CHILD、SELF、CUSTOM 数据范围。'
      WHEN 'resource_acl' THEN '资源级授权表，用于记录具体 Agent、知识库、工具、模型等资源授权给用户、角色、部门或租户主体的 ACL 规则。'
      WHEN 'api_key' THEN '租户接口密钥表，用于管理外部系统调用 Agent 的机器密钥、调用范围、限流和额度。'
      WHEN 'system_setting' THEN '系统设置参数表，用于按租户维护基础、安全、运行时、观测、数据保留和集成配置。'
      WHEN 'login_log' THEN '登录日志表。'
      WHEN 'operation_log' THEN '操作日志表。'
      WHEN 'refresh_token' THEN '刷新令牌表。'
      WHEN 'agent_category' THEN '智能体分类表。'
      WHEN 'agent' THEN '智能体主表。'
      WHEN 'agent_version' THEN '智能体版本快照表。'
      WHEN 'agent_model_binding' THEN '智能体与模型绑定表。'
      WHEN 'agent_prompt_binding' THEN '智能体与提示词绑定表。'
      WHEN 'agent_knowledge_binding' THEN '智能体与知识库绑定表。'
      WHEN 'agent_tool_binding' THEN '智能体与工具绑定表。'
      WHEN 'agent_publish_channel' THEN '智能体发布渠道表。'
      WHEN 'agent_audit_log' THEN '智能体审计日志表。'
      WHEN 'model_provider' THEN '模型供应商表。'
      WHEN 'model_config' THEN '模型配置表。'
      WHEN 'model_api_key' THEN '模型供应商密钥表。'
      WHEN 'model_cost_rule' THEN '模型成本规则表。'
      WHEN 'model_call_log' THEN '模型调用日志表。'
      WHEN 'prompt_template' THEN '提示词模板表。'
      WHEN 'prompt_version' THEN '提示词版本快照表。'
      WHEN 'prompt_variable' THEN '提示词变量表。'
      WHEN 'prompt_test_record' THEN '提示词测试记录表。'
      WHEN 'knowledge_base' THEN '知识库主表。'
      WHEN 'knowledge_document' THEN '知识文档表。'
      WHEN 'knowledge_segment' THEN '知识切片表。'
      WHEN 'knowledge_embedding_task' THEN '知识处理任务表。'
      WHEN 'knowledge_recall_log' THEN '知识召回日志表。'
      WHEN 'tool' THEN '工具主表。'
      WHEN 'tool_call_log' THEN '工具调用日志表。'
      WHEN 'tool_approval_request' THEN '工具审批请求表。'
      WHEN 'conversation' THEN '会话主表。'
      WHEN 'conversation_run' THEN '会话运行记录表。'
      WHEN 'conversation_message' THEN '会话消息表。'
      WHEN 'conversation_feedback' THEN '会话反馈表。'
      WHEN 'security_policy' THEN '安全策略中心的 ABAC 策略表，用于定义租户级资源访问允许或拒绝规则。'
      WHEN 'security_policy_evaluation' THEN '安全策略评估日志表，记录 ABAC 模拟和运行时评估结果。'
      ELSE format('业务表：%s。', table_record.table_name)
    END;

    EXECUTE format('COMMENT ON TABLE public.%I IS %L', table_record.table_name, comment_text);
  END LOOP;

  FOR column_record IN
    SELECT table_name, column_name
    FROM information_schema.columns
    WHERE table_schema = 'public'
  LOOP
    comment_text := CASE
      WHEN column_record.table_name = '_prisma_migrations' AND column_record.column_name = 'id' THEN '迁移记录主键。'
      WHEN column_record.table_name = '_prisma_migrations' AND column_record.column_name = 'checksum' THEN '迁移脚本校验和。'
      WHEN column_record.table_name = '_prisma_migrations' AND column_record.column_name = 'finished_at' THEN '迁移完成时间。'
      WHEN column_record.table_name = '_prisma_migrations' AND column_record.column_name = 'migration_name' THEN '迁移名称。'
      WHEN column_record.table_name = '_prisma_migrations' AND column_record.column_name = 'logs' THEN '迁移日志内容。'
      WHEN column_record.table_name = '_prisma_migrations' AND column_record.column_name = 'rolled_back_at' THEN '迁移回滚时间。'
      WHEN column_record.table_name = '_prisma_migrations' AND column_record.column_name = 'started_at' THEN '迁移开始时间。'
      WHEN column_record.table_name = '_prisma_migrations' AND column_record.column_name = 'applied_steps_count' THEN '已执行步骤数量。'
      WHEN column_record.column_name = 'id' THEN '主键 ID。'
      WHEN column_record.column_name = 'tenant_id' THEN '所属租户 ID。'
      WHEN column_record.column_name = 'user_id' THEN '关联用户 ID。'
      WHEN column_record.column_name = 'department_id' THEN '用户所属部门 ID。'
      WHEN column_record.column_name = 'role_id' THEN '关联角色 ID。'
      WHEN column_record.column_name = 'permission_id' THEN '关联权限 ID。'
      WHEN column_record.column_name = 'menu_id' THEN '关联菜单 ID。'
      WHEN column_record.table_name = 'department' AND column_record.column_name = 'parent_id' THEN '父级部门 ID，空值表示根部门。'
      WHEN column_record.column_name = 'parent_id' THEN '父级菜单 ID。'
      WHEN column_record.column_name = 'leader_user_id' THEN '部门负责人用户 ID。'
      WHEN column_record.column_name = 'agent_id' THEN '关联智能体 ID。'
      WHEN column_record.column_name = 'category_id' THEN '关联分类 ID。'
      WHEN column_record.column_name = 'owner_id' THEN '负责人用户 ID。'
      WHEN column_record.column_name = 'provider_id' THEN '关联模型供应商 ID。'
      WHEN column_record.column_name = 'model_config_id' THEN '关联模型配置 ID。'
      WHEN column_record.column_name = 'knowledge_id' THEN '关联知识库 ID。'
      WHEN column_record.column_name = 'document_id' THEN '关联知识文档 ID。'
      WHEN column_record.column_name = 'template_id' THEN '关联提示词模板 ID。'
      WHEN column_record.column_name = 'tool_id' THEN '关联工具 ID。'
      WHEN column_record.column_name = 'tool_call_log_id' THEN '关联工具调用日志 ID。'
      WHEN column_record.column_name = 'conversation_id' THEN '关联会话 ID。'
      WHEN column_record.column_name = 'run_id' THEN '关联运行记录 ID。'
      WHEN column_record.column_name = 'created_by' THEN '创建人用户 ID。'
      WHEN column_record.column_name = 'updated_by' THEN '最近更新人用户 ID。'
      WHEN column_record.column_name = 'requested_by' THEN '申请人用户 ID。'
      WHEN column_record.column_name = 'reviewed_by' THEN '审批人用户 ID。'
      WHEN column_record.column_name = 'uploaded_by' THEN '上传人用户 ID。'
      WHEN column_record.column_name = 'code' THEN '业务编码。'
      WHEN column_record.column_name = 'name' THEN '名称。'
      WHEN column_record.column_name = 'status' THEN '当前状态。'
      WHEN column_record.column_name = 'description' THEN '描述信息。'
      WHEN column_record.column_name = 'component' THEN '前端组件标识。'
      WHEN column_record.column_name = 'icon' THEN '图标标识。'
      WHEN column_record.column_name = 'permission_code' THEN '访问所需权限编码。'
      WHEN column_record.column_name = 'sort_order' THEN '排序号。'
      WHEN column_record.column_name = 'visible' THEN '是否在导航中显示。'
      WHEN column_record.column_name = 'enabled' THEN '是否启用。'
      WHEN column_record.column_name = 'email' THEN '邮箱地址。'
      WHEN column_record.column_name = 'password_hash' THEN '密码哈希值。'
      WHEN column_record.column_name = 'key_prefix' THEN '密钥前缀。'
      WHEN column_record.column_name = 'key_hash' THEN '密钥哈希值。'
      WHEN column_record.column_name = 'scopes' THEN '接口密钥授权范围 JSON，例如 external:agent:chat、external:agent:stream。'
      WHEN column_record.column_name = 'allowed_agent_ids' THEN '允许外部调用的 Agent ID 白名单 JSON 数组，空数组表示不限制 Agent。'
      WHEN column_record.column_name = 'ip_allowlist' THEN '允许调用的客户端 IP 白名单 JSON 数组，空数组表示不限制 IP。'
      WHEN column_record.column_name = 'rate_limit_per_minute' THEN '每分钟调用次数上限。'
      WHEN column_record.column_name = 'daily_quota' THEN '每日调用额度，空值表示不限每日总量。'
      WHEN column_record.column_name = 'used_count_today' THEN '今日已使用次数。'
      WHEN column_record.column_name = 'quota_reset_date' THEN '每日额度计数日期，用于跨天重置 used_count_today。'
      WHEN column_record.column_name = 'allow_stream' THEN '是否允许使用外部流式调用。'
      WHEN column_record.table_name = 'system_setting' AND column_record.column_name = 'category' THEN '设置分类，GENERAL 基础、SECURITY 安全、RUNTIME 运行时、OBSERVABILITY 观测、RETENTION 数据保留、INTEGRATION 外部集成。'
      WHEN column_record.table_name = 'system_setting' AND column_record.column_name = 'key' THEN '设置键名，在租户内唯一。'
      WHEN column_record.table_name = 'system_setting' AND column_record.column_name = 'value' THEN '当前设置值，使用 JSONB 存储以兼容文本、数字、布尔、对象和数组。'
      WHEN column_record.table_name = 'system_setting' AND column_record.column_name = 'default_value' THEN '默认设置值，用于恢复默认和判断是否偏离默认。'
      WHEN column_record.table_name = 'system_setting' AND column_record.column_name = 'value_type' THEN '设置值类型，STRING、NUMBER、BOOLEAN、JSON、SELECT。'
      WHEN column_record.table_name = 'system_setting' AND column_record.column_name = 'options' THEN '下拉或枚举选项 JSON 数组。'
      WHEN column_record.table_name = 'system_setting' AND column_record.column_name = 'is_secret' THEN '是否为敏感设置，敏感值前端默认脱敏展示。'
      WHEN column_record.table_name = 'system_setting' AND column_record.column_name = 'is_system' THEN '是否为系统内置设置。'
      WHEN column_record.column_name = 'last_used_at' THEN '最近使用时间。'
      WHEN column_record.column_name = 'last_login_at' THEN '最近登录时间。'
      WHEN column_record.column_name = 'created_at' THEN '创建时间。'
      WHEN column_record.column_name = 'updated_at' THEN '更新时间。'
      WHEN column_record.column_name = 'deleted_at' THEN '软删除时间。'
      WHEN column_record.column_name = 'expires_at' THEN '过期时间。'
      WHEN column_record.column_name = 'revoked_at' THEN '撤销时间。'
      WHEN column_record.column_name = 'module' THEN '所属模块。'
      WHEN column_record.table_name = 'permission' AND column_record.column_name = 'resource' THEN '权限资源编码，配合 module 和 action 组成 module:resource:action 标准权限编码。'
      WHEN column_record.column_name = 'resource' THEN '被访问资源属性 JSON。'
      WHEN column_record.column_name = 'action' THEN '动作类型。'
      WHEN column_record.column_name = 'effect' THEN '策略效果，ALLOW 表示允许，DENY 表示拒绝。'
      WHEN column_record.column_name = 'resource_type' THEN '资源类型，例如 AGENT、KNOWLEDGE_BASE、DOCUMENT、TOOL、MODEL、CONVERSATION、AUDIT_LOG。'
      WHEN column_record.column_name = 'resource_id' THEN '被授权资源 ID。'
      WHEN column_record.column_name = 'subject_type' THEN '授权主体类型，USER 用户、ROLE 角色、DEPARTMENT 部门、TENANT 租户。'
      WHEN column_record.column_name = 'subject_id' THEN '授权主体 ID。'
      WHEN column_record.column_name = 'scope_type' THEN '数据范围类型，ALL 全部数据、TENANT 本租户、DEPT 本部门、DEPT_AND_CHILD 本部门及子部门、SELF 本人、CUSTOM 自定义。'
      WHEN column_record.column_name = 'scope_value' THEN '数据范围配置 JSON，包含 department_ids、user_ids、resource_ids、include_children 等自定义范围。'
      WHEN column_record.column_name = 'priority' THEN '策略优先级，数值越大越先匹配。'
      WHEN column_record.column_name = 'conditions' THEN 'ABAC 条件 JSON，包含 subject、resource、context 属性路径与操作符。'
      WHEN column_record.column_name = 'subject' THEN '访问主体属性 JSON。'
      WHEN column_record.column_name = 'decision' THEN '策略评估结果。'
      WHEN column_record.column_name = 'matched_policy_id' THEN '命中的安全策略 ID。'
      WHEN column_record.column_name = 'matched_policy_code' THEN '命中的安全策略编码快照。'
      WHEN column_record.column_name = 'method' THEN 'HTTP 方法。'
      WHEN column_record.column_name = 'path' THEN '请求路径。'
      WHEN column_record.column_name = 'status_code' THEN 'HTTP 状态码。'
      WHEN column_record.column_name = 'request_id' THEN '请求链路 ID。'
      WHEN column_record.column_name = 'ip' THEN '客户端 IP 地址。'
      WHEN column_record.column_name = 'user_agent' THEN '客户端标识。'
      WHEN column_record.column_name = 'request_summary' THEN '请求摘要 JSON。'
      WHEN column_record.column_name = 'error_message' THEN '错误信息。'
      WHEN column_record.column_name = 'decision_note' THEN '审批备注。'
      WHEN column_record.column_name = 'token_hash' THEN '令牌哈希值。'
      WHEN column_record.column_name = 'version' THEN '版本号。'
      WHEN column_record.column_name = 'snapshot' THEN '快照数据 JSON。'
      WHEN column_record.column_name = 'change_note' THEN '变更说明。'
      WHEN column_record.column_name = 'published_at' THEN '发布时间。'
      WHEN column_record.column_name = 'model_id' THEN '关联模型标识。'
      WHEN column_record.column_name = 'binding_type' THEN '绑定类型。'
      WHEN column_record.column_name = 'weight' THEN '权重值。'
      WHEN column_record.column_name = 'prompt_id' THEN '关联提示词标识。'
      WHEN column_record.column_name = 'prompt_type' THEN '提示词类型。'
      WHEN column_record.column_name = 'recall_top_k' THEN '召回 TopK 数量。'
      WHEN column_record.column_name = 'require_approval' THEN '是否需要审批。'
      WHEN column_record.column_name = 'channel' THEN '渠道标识。'
      WHEN column_record.column_name = 'config' THEN '配置 JSON。'
      WHEN column_record.column_name = 'message' THEN '消息内容。'
      WHEN column_record.column_name = 'metadata' THEN '附加元数据 JSON。'
      WHEN column_record.column_name = 'provider_type' THEN '供应商类型。'
      WHEN column_record.column_name = 'base_url' THEN '基础调用地址。'
      WHEN column_record.column_name = 'is_default' THEN '是否默认。'
      WHEN column_record.column_name = 'model' THEN '模型标识。'
      WHEN column_record.column_name = 'capabilities' THEN '能力列表。'
      WHEN column_record.column_name = 'context_length' THEN '上下文长度。'
      WHEN column_record.column_name = 'input_price' THEN '输入价格。'
      WHEN column_record.column_name = 'output_price' THEN '输出价格。'
      WHEN column_record.column_name = 'rate_limit_rpm' THEN '每分钟限流。'
      WHEN column_record.column_name = 'masked_key' THEN '脱敏后的密钥。'
      WHEN column_record.column_name = 'encrypted_key' THEN '加密后的密钥。'
      WHEN column_record.column_name = 'currency' THEN '货币类型。'
      WHEN column_record.column_name = 'unit' THEN '计费单位。'
      WHEN column_record.column_name = 'effective_from' THEN '生效时间。'
      WHEN column_record.column_name = 'trace_id' THEN '追踪链路 ID。'
      WHEN column_record.column_name = 'request_model' THEN '请求使用的模型标识。'
      WHEN column_record.column_name = 'prompt_tokens' THEN '输入词元数。'
      WHEN column_record.column_name = 'completion_tokens' THEN '输出词元数。'
      WHEN column_record.column_name = 'total_tokens' THEN '总词元数。'
      WHEN column_record.column_name = 'input_cost' THEN '输入成本。'
      WHEN column_record.column_name = 'output_cost' THEN '输出成本。'
      WHEN column_record.column_name = 'total_cost' THEN '总成本。'
      WHEN column_record.column_name = 'latency_ms' THEN '延迟毫秒数。'
      WHEN column_record.column_name = 'response_summary' THEN '响应摘要 JSON。'
      WHEN column_record.column_name = 'type' THEN '类型。'
      WHEN column_record.column_name = 'content' THEN '内容。'
      WHEN column_record.column_name = 'variable_type' THEN '变量类型。'
      WHEN column_record.column_name = 'default_value' THEN '默认值。'
      WHEN column_record.column_name = 'is_required' THEN '是否必填。'
      WHEN column_record.column_name = 'sort_order' THEN '排序号。'
      WHEN column_record.column_name = 'inputs' THEN '输入参数 JSON。'
      WHEN column_record.column_name = 'rendered_content' THEN '渲染后的内容。'
      WHEN column_record.column_name = 'output_text' THEN '输出文本。'
      WHEN column_record.column_name = 'visibility' THEN '可见范围。'
      WHEN column_record.column_name = 'source_type' THEN '来源类型。'
      WHEN column_record.column_name = 'mime_type' THEN 'MIME 类型。'
      WHEN column_record.column_name = 'file_name' THEN '文件名。'
      WHEN column_record.column_name = 'file_size' THEN '文件大小（字节）。'
      WHEN column_record.column_name = 'storage_path' THEN '存储路径。'
      WHEN column_record.column_name = 'checksum' THEN '内容校验和。'
      WHEN column_record.column_name = 'parsed_text' THEN '解析后的文本内容。'
      WHEN column_record.column_name = 'segment_count' THEN '切片数量。'
      WHEN column_record.column_name = 'token_count' THEN '词元数量。'
      WHEN column_record.column_name = 'keywords' THEN '关键词数组。'
      WHEN column_record.column_name = 'embedding_vector' THEN '切片嵌入向量。'
      WHEN column_record.column_name = 'embedding_model' THEN '生成嵌入所使用的模型标识。'
      WHEN column_record.column_name = 'vector_status' THEN '向量状态。'
      WHEN column_record.column_name = 'index_status' THEN '索引状态。'
      WHEN column_record.column_name = 'task_type' THEN '任务类型。'
      WHEN column_record.column_name = 'total_items' THEN '总项目数量。'
      WHEN column_record.column_name = 'processed_items' THEN '已处理项目数量。'
      WHEN column_record.column_name = 'started_at' THEN '开始时间。'
      WHEN column_record.column_name = 'ended_at' THEN '结束时间。'
      WHEN column_record.column_name = 'reviewed_at' THEN '审批时间。'
      WHEN column_record.column_name = 'query' THEN '查询内容。'
      WHEN column_record.column_name = 'mode' THEN '模式。'
      WHEN column_record.column_name = 'top_k' THEN 'Top K 数量。'
      WHEN column_record.column_name = 'result_count' THEN '结果数量。'
      WHEN column_record.column_name = 'results' THEN '结果明细 JSON。'
      WHEN column_record.column_name = 'tool_type' THEN '工具类型。'
      WHEN column_record.column_name = 'risk_level' THEN '风险等级。'
      WHEN column_record.column_name = 'timeout_ms' THEN '超时时间（毫秒）。'
      WHEN column_record.column_name = 'headers' THEN '默认请求头 JSON。'
      WHEN column_record.column_name = 'auth_type' THEN '鉴权类型。'
      WHEN column_record.column_name = 'auth_config' THEN '鉴权配置 JSON。'
      WHEN column_record.column_name = 'input_schema' THEN '输入结构 JSON Schema。'
      WHEN column_record.column_name = 'output_schema' THEN '输出结构 JSON Schema。'
      WHEN column_record.column_name = 'trigger_source' THEN '触发来源。'
      WHEN column_record.column_name = 'request_url' THEN '请求 URL。'
      WHEN column_record.column_name = 'request_method' THEN '请求方法。'
      WHEN column_record.column_name = 'request_headers' THEN '请求头 JSON。'
      WHEN column_record.column_name = 'request_body' THEN '请求体 JSON。'
      WHEN column_record.column_name = 'reason' THEN '申请原因。'
      WHEN column_record.column_name = 'response_status' THEN '响应状态码。'
      WHEN column_record.column_name = 'response_headers' THEN '响应头 JSON。'
      WHEN column_record.column_name = 'response_body' THEN '响应体 JSON。'
      WHEN column_record.column_name = 'message_count' THEN '消息数量。'
      WHEN column_record.column_name = 'last_message_preview' THEN '最近消息预览。'
      WHEN column_record.column_name = 'last_message_at' THEN '最近消息时间。'
      WHEN column_record.column_name = 'last_run_status' THEN '最近运行状态。'
      WHEN column_record.column_name = 'steps' THEN '运行步骤 JSON。'
      WHEN column_record.column_name = 'references' THEN '引用列表 JSON。'
      WHEN column_record.column_name = 'tool_calls' THEN '工具调用列表 JSON。'
      WHEN column_record.column_name = 'rating' THEN '评分。'
      WHEN column_record.column_name = 'comment' THEN '备注评论。'
      ELSE format('字段：%s。', column_record.column_name)
    END;

    EXECUTE format(
      'COMMENT ON COLUMN public.%I.%I IS %L',
      column_record.table_name,
      column_record.column_name,
      comment_text
    );
  END LOOP;
END $$;
