DO $$
DECLARE
  table_record RECORD;
  column_record RECORD;
  comment_text TEXT;
BEGIN
  FOR table_record IN
    SELECT table_name
    FROM information_schema.tables
    WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
  LOOP
    comment_text := CASE table_record.table_name
      WHEN '_prisma_migrations' THEN 'Prisma 迁移历史表。'
      WHEN 'tenant' THEN '租户主表。'
      WHEN 'user' THEN '用户主表。'
      WHEN 'department' THEN '部门组织架构表，用于维护租户内部门树、负责人和成员归属。'
      WHEN 'role' THEN '角色定义表。'
      WHEN 'permission' THEN '权限定义表。'
      WHEN 'user_role' THEN '用户与角色关联表。'
      WHEN 'role_permission' THEN '角色与权限关联表。'
      WHEN 'menu' THEN '控制台菜单表，用于配置目录、页面和按钮节点。'
      WHEN 'role_menu' THEN '角色与菜单关联表，用于控制角色可见菜单和按钮。'
      WHEN 'role_data_scope' THEN '角色数据权限范围表，用于按角色和资源类型配置 ALL、TENANT、DEPT、DEPT_AND_CHILD、SELF、CUSTOM 数据范围。'
      WHEN 'resource_acl' THEN '资源级授权表，用于记录具体 Agent、知识库、工具、模型等资源授权给用户、角色、部门或租户主体的 ACL 规则。'
      WHEN 'api_key' THEN '租户接口密钥表，用于管理外部系统调用 Agent 的机器密钥、调用范围、限流、额度和运行完成 Webhook 回调。'
      WHEN 'system_setting' THEN '系统设置参数表，用于按租户维护基础、安全、运行时、观测、数据保留和集成配置。'
      WHEN 'system_setting_snapshot' THEN '系统设置版本快照表，用于记录租户级系统设置变更前后的值、状态、审批预留和回滚来源。'
      WHEN 'approval_audit_event' THEN '审批审计事件表，用于统一记录工具审批、通知策略审批及后续审批源的生命周期事件。'
      WHEN 'login_log' THEN '登录日志表。'
      WHEN 'operation_log' THEN '操作日志表。'
      WHEN 'refresh_token' THEN '刷新令牌表。'
      WHEN 'agent_category' THEN '智能体分类表。'
      WHEN 'agent' THEN '智能体主表。'
      WHEN 'agent_version' THEN '智能体版本快照表。'
      WHEN 'agent_model_binding' THEN '智能体与模型绑定表。'
      WHEN 'agent_prompt_binding' THEN '智能体与提示词绑定表。'
      WHEN 'agent_knowledge_binding' THEN '智能体与知识库绑定表。'
      WHEN 'agent_tool_binding' THEN '智能体与工具绑定表。'
      WHEN 'agent_publish_channel' THEN '智能体发布渠道表，用于维护 Agent 在 Web、开放 API、企业微信、钉钉、飞书等渠道的发布配置、健康状态和回调入口。'
      WHEN 'channel_sender_delivery' THEN '渠道主动回复投递表，用于记录主动回复发送的请求、响应、失败原因、重试链路和审计上下文。'
      WHEN 'agent_audit_log' THEN '智能体审计日志表。'
      WHEN 'agent_team' THEN 'Agent 协作团队主表，用于配置多 Agent 团队的协作模式、负责人、执行轮次、超时和接力策略。'
      WHEN 'agent_team_member' THEN 'Agent 协作团队成员表，用于配置团队内 Agent 的角色、职责、执行顺序和启用状态。'
      WHEN 'agent_team_run' THEN 'Agent 协作团队运行记录表，用于记录团队任务目标、状态、Trace、步骤统计、Token、成本和耗时。'
      WHEN 'agent_team_step' THEN 'Agent 协作团队运行步骤表，用于记录每个成员 Agent 的规划、执行、校验、接力等步骤轨迹。'
      WHEN 'agent_team_handoff' THEN 'Agent 协作团队接力记录表，用于记录成员 Agent 之间的接力原因、目标、状态和人工决策。'
      WHEN 'agent_team_feedback' THEN 'Agent 协作团队运行反馈表，用于记录团队任务结果评分和人工反馈。'
      WHEN 'model_provider' THEN '模型供应商表。'
      WHEN 'model_config' THEN '模型配置表。'
      WHEN 'model_api_key' THEN '模型供应商密钥表。'
      WHEN 'model_cost_rule' THEN '模型成本规则表。'
      WHEN 'model_call_log' THEN '模型调用日志表。'
      WHEN 'prompt_template' THEN '提示词模板表。'
      WHEN 'prompt_version' THEN '提示词版本快照表。'
      WHEN 'prompt_variable' THEN '提示词变量表。'
      WHEN 'prompt_test_record' THEN '提示词测试记录表。'
      WHEN 'knowledge_base' THEN '知识库主表。'
      WHEN 'knowledge_document' THEN '知识文档表。'
      WHEN 'knowledge_segment' THEN '知识切片表。'
      WHEN 'knowledge_embedding_task' THEN '知识处理任务表。'
      WHEN 'knowledge_recall_log' THEN '知识召回日志表。'
      WHEN 'tool' THEN '工具主表。'
      WHEN 'tool_call_log' THEN '工具调用日志表。'
      WHEN 'tool_approval_request' THEN '工具审批请求表。'
      WHEN 'conversation' THEN '会话主表。'
      WHEN 'conversation_run' THEN '会话运行记录表。'
      WHEN 'conversation_message' THEN '会话消息表。'
      WHEN 'conversation_feedback' THEN '会话反馈表。'
      WHEN 'security_policy' THEN '安全策略中心的 ABAC 策略表，用于定义租户级资源访问允许或拒绝规则。'
      WHEN 'security_policy_evaluation' THEN '安全策略评估日志表，记录 ABAC 模拟和运行时评估结果。'
      WHEN 'platform_event' THEN '平台统一事件表，用于投影 Agent、团队、工具、知识库、渠道、插件、安全和工作流等平台事件。'
      WHEN 'platform_usage_event' THEN '平台统一用量事件表，用于记录模型 Token、工具调用、知识检索、工作流步骤、渠道投递和存储等可聚合用量。'
      WHEN 'platform_event_relation' THEN '平台统一事件关系表，用于记录父子、重试、接力、审批和结算归因链路。'
      WHEN 'platform_usage_rollup' THEN '平台统一用量汇总表，用于按租户、主体、资源和周期汇总事件数量、用量、金额、错误和重试。'
      WHEN 'billing_plan' THEN '计费套餐表，用于定义租户可选套餐、价格、包含额度、功能限制和超额计价规则。'
      WHEN 'tenant_subscription' THEN '租户订阅表，用于记录租户当前套餐、计费周期、订阅状态、周期额度和自动续费配置。'
      WHEN 'billing_invoice' THEN '账单表，用于记录租户账期账单、金额、支付状态、到期时间和账单明细。'
      WHEN 'billing_quota_policy' THEN '计费额度策略表，用于配置租户、用户、API Key、Agent 等主体的成本、词元、调用次数额度与超限动作。'
      WHEN 'plugin' THEN '插件主表，用于维护插件市场条目、租户可安装插件元数据、风险等级、运行状态和能力统计。'
      WHEN 'plugin_version' THEN '插件版本表，用于记录插件版本、Manifest 快照、发布状态和变更说明。'
      WHEN 'plugin_installation' THEN '插件安装实例表，用于记录租户内插件安装版本、运行状态、配置、权限预览和生命周期时间。'
      WHEN 'plugin_hook' THEN '插件 Hook 表，用于记录插件接入平台事件、用量聚合、工具网关或控制面扩展点的绑定配置。'
      WHEN 'plugin_menu_binding' THEN '插件菜单绑定表，用于记录插件注入或绑定到控制台菜单入口的可见性、启用状态和排序。'
      WHEN 'plugin_audit_log' THEN '插件审计日志表，用于记录插件安装、启停、升级、配置、Hook 和菜单注入变更。'
      ELSE format('业务表：%s。', table_record.table_name)
    END;

    EXECUTE format('COMMENT ON TABLE public.%I IS %L', table_record.table_name, comment_text);
  END LOOP;

  FOR column_record IN
    SELECT table_name, column_name
    FROM information_schema.columns
    WHERE table_schema = 'public'
  LOOP
    comment_text := CASE
      WHEN column_record.table_name = '_prisma_migrations' AND column_record.column_name = 'id' THEN '迁移记录主键。'
      WHEN column_record.table_name = '_prisma_migrations' AND column_record.column_name = 'checksum' THEN '迁移脚本校验和。'
      WHEN column_record.table_name = '_prisma_migrations' AND column_record.column_name = 'finished_at' THEN '迁移完成时间。'
      WHEN column_record.table_name = '_prisma_migrations' AND column_record.column_name = 'migration_name' THEN '迁移名称。'
      WHEN column_record.table_name = '_prisma_migrations' AND column_record.column_name = 'logs' THEN '迁移日志内容。'
      WHEN column_record.table_name = '_prisma_migrations' AND column_record.column_name = 'rolled_back_at' THEN '迁移回滚时间。'
      WHEN column_record.table_name = '_prisma_migrations' AND column_record.column_name = 'started_at' THEN '迁移开始时间。'
      WHEN column_record.table_name = '_prisma_migrations' AND column_record.column_name = 'applied_steps_count' THEN '已执行步骤数量。'
      WHEN column_record.column_name = 'id' THEN '主键 ID。'
      WHEN column_record.column_name = 'tenant_id' THEN '所属租户 ID。'
      WHEN column_record.column_name = 'user_id' THEN '关联用户 ID。'
      WHEN column_record.column_name = 'department_id' THEN '用户所属部门 ID。'
      WHEN column_record.column_name = 'role_id' THEN '关联角色 ID。'
      WHEN column_record.column_name = 'permission_id' THEN '关联权限 ID。'
      WHEN column_record.column_name = 'menu_id' THEN '关联菜单 ID。'
      WHEN column_record.table_name = 'department' AND column_record.column_name = 'parent_id' THEN '父级部门 ID，空值表示根部门。'
      WHEN column_record.column_name = 'parent_id' THEN '父级菜单 ID。'
      WHEN column_record.column_name = 'leader_user_id' THEN '部门负责人用户 ID。'
      WHEN column_record.column_name = 'agent_id' THEN '关联智能体 ID。'
      WHEN column_record.column_name = 'team_id' THEN '关联 Agent 协作团队 ID。'
      WHEN column_record.column_name = 'member_id' THEN '关联 Agent 协作团队成员 ID。'
      WHEN column_record.column_name = 'from_member_id' THEN '来源 Agent 协作团队成员 ID。'
      WHEN column_record.column_name = 'to_member_id' THEN '目标 Agent 协作团队成员 ID。'
      WHEN column_record.column_name = 'from_agent_id' THEN '来源智能体 ID。'
      WHEN column_record.column_name = 'to_agent_id' THEN '目标智能体 ID。'
      WHEN column_record.column_name = 'category_id' THEN '关联分类 ID。'
      WHEN column_record.column_name = 'owner_id' THEN '负责人用户 ID。'
      WHEN column_record.column_name = 'provider_id' THEN '关联模型供应商 ID。'
      WHEN column_record.column_name = 'model_config_id' THEN '关联模型配置 ID。'
      WHEN column_record.column_name = 'knowledge_id' THEN '关联知识库 ID。'
      WHEN column_record.column_name = 'document_id' THEN '关联知识文档 ID。'
      WHEN column_record.column_name = 'template_id' THEN '关联提示词模板 ID。'
      WHEN column_record.column_name = 'tool_id' THEN '关联工具 ID。'
      WHEN column_record.column_name = 'tool_call_log_id' THEN '关联工具调用日志 ID。'
      WHEN column_record.column_name = 'conversation_id' THEN '关联会话 ID。'
      WHEN column_record.column_name = 'run_id' THEN '关联运行记录 ID。'
      WHEN column_record.column_name = 'created_by' THEN '创建人用户 ID。'
      WHEN column_record.column_name = 'updated_by' THEN '最近更新人用户 ID。'
      WHEN column_record.column_name = 'requested_by' THEN '申请人用户 ID。'
      WHEN column_record.column_name = 'reviewed_by' THEN '审批人用户 ID。'
      WHEN column_record.column_name = 'uploaded_by' THEN '上传人用户 ID。'
      WHEN column_record.column_name = 'code' THEN '业务编码。'
      WHEN column_record.column_name = 'name' THEN '名称。'
      WHEN column_record.column_name = 'status' THEN '当前状态。'
      WHEN column_record.column_name = 'description' THEN '描述信息。'
      WHEN column_record.column_name = 'component' THEN '前端组件标识。'
      WHEN column_record.column_name = 'icon' THEN '图标标识。'
      WHEN column_record.column_name = 'permission_code' THEN '访问所需权限编码。'
      WHEN column_record.column_name = 'sort_order' THEN '排序号。'
      WHEN column_record.column_name = 'visible' THEN '是否在导航中显示。'
      WHEN column_record.column_name = 'enabled' THEN '是否启用。'
      WHEN column_record.column_name = 'email' THEN '邮箱地址。'
      WHEN column_record.column_name = 'password_hash' THEN '密码哈希值。'
      WHEN column_record.column_name = 'key_prefix' THEN '密钥前缀。'
      WHEN column_record.column_name = 'key_hash' THEN '密钥哈希值。'
      WHEN column_record.column_name = 'scopes' THEN '接口密钥授权范围 JSON，例如 external:agent:chat、external:agent:stream。'
      WHEN column_record.column_name = 'allowed_agent_ids' THEN '允许外部调用的 Agent ID 白名单 JSON 数组，空数组表示不限制 Agent。'
      WHEN column_record.column_name = 'ip_allowlist' THEN '允许调用的客户端 IP 白名单 JSON 数组，空数组表示不限制 IP。'
      WHEN column_record.column_name = 'rate_limit_per_minute' THEN '每分钟调用次数上限。'
      WHEN column_record.column_name = 'daily_quota' THEN '每日调用额度，空值表示不限每日总量。'
      WHEN column_record.column_name = 'used_count_today' THEN '今日已使用次数。'
      WHEN column_record.column_name = 'quota_reset_date' THEN '每日额度计数日期，用于跨天重置 used_count_today。'
      WHEN column_record.column_name = 'allow_stream' THEN '是否允许使用外部流式调用。'
      WHEN column_record.column_name = 'webhook_enabled' THEN '是否启用外部 API 调用完成 Webhook 回调。'
      WHEN column_record.column_name = 'webhook_url' THEN 'Webhook 回调地址，外部调用完成后向该地址发送 POST 通知。'
      WHEN column_record.column_name = 'webhook_events' THEN 'Webhook 订阅事件 JSON 数组，例如 agent.run.completed。'
      WHEN column_record.column_name = 'webhook_secret_encrypted' THEN 'Webhook 签名密钥密文，用于生成 x-aiaget-signature HMAC 签名。'
      WHEN column_record.column_name = 'webhook_last_status' THEN '最近一次 Webhook 投递状态，SUCCESS 成功、FAILED 失败、SKIPPED 跳过。'
      WHEN column_record.column_name = 'webhook_last_error' THEN '最近一次 Webhook 投递失败原因。'
      WHEN column_record.column_name = 'webhook_last_sent_at' THEN '最近一次 Webhook 投递时间。'
      WHEN column_record.table_name = 'system_setting' AND column_record.column_name = 'category' THEN '设置分类，GENERAL 基础、SECURITY 安全、RUNTIME 运行时、OBSERVABILITY 观测、RETENTION 数据保留、INTEGRATION 外部集成。'
      WHEN column_record.table_name = 'system_setting' AND column_record.column_name = 'key' THEN '设置键名，在租户内唯一。'
      WHEN column_record.table_name = 'system_setting' AND column_record.column_name = 'value' THEN '当前设置值，使用 JSONB 存储以兼容文本、数字、布尔、对象和数组。'
      WHEN column_record.table_name = 'system_setting' AND column_record.column_name = 'default_value' THEN '默认设置值，用于恢复默认和判断是否偏离默认。'
      WHEN column_record.table_name = 'system_setting' AND column_record.column_name = 'value_type' THEN '设置值类型，STRING、NUMBER、BOOLEAN、JSON、SELECT。'
      WHEN column_record.table_name = 'system_setting' AND column_record.column_name = 'options' THEN '下拉或枚举选项 JSON 数组。'
      WHEN column_record.table_name = 'system_setting' AND column_record.column_name = 'is_secret' THEN '是否为敏感设置，敏感值前端默认脱敏展示。'
      WHEN column_record.table_name = 'system_setting' AND column_record.column_name = 'is_system' THEN '是否为系统内置设置。'
      WHEN column_record.table_name = 'system_setting_snapshot' AND column_record.column_name = 'setting_id' THEN '关联系统设置 ID。'
      WHEN column_record.table_name = 'system_setting_snapshot' AND column_record.column_name = 'setting_key' THEN '系统设置键名快照。'
      WHEN column_record.table_name = 'system_setting_snapshot' AND column_record.column_name = 'setting_name' THEN '系统设置名称快照。'
      WHEN column_record.table_name = 'system_setting_snapshot' AND column_record.column_name = 'version' THEN '该设置在租户内的递增版本号。'
      WHEN column_record.table_name = 'system_setting_snapshot' AND column_record.column_name = 'action' THEN '快照动作，UPDATE 更新、RESET 恢复默认、ROLLBACK 回滚。'
      WHEN column_record.table_name = 'system_setting_snapshot' AND column_record.column_name = 'previous_value' THEN '变更前设置值。'
      WHEN column_record.table_name = 'system_setting_snapshot' AND column_record.column_name = 'next_value' THEN '变更后设置值。'
      WHEN column_record.table_name = 'system_setting_snapshot' AND column_record.column_name = 'previous_status' THEN '变更前设置状态。'
      WHEN column_record.table_name = 'system_setting_snapshot' AND column_record.column_name = 'next_status' THEN '变更后设置状态。'
      WHEN column_record.table_name = 'system_setting_snapshot' AND column_record.column_name = 'approval_status' THEN '审批状态预留，NOT_REQUIRED 不需要审批、RESERVED 预留、PENDING 待审批、APPROVED 已通过、REJECTED 已拒绝。'
      WHEN column_record.table_name = 'system_setting_snapshot' AND column_record.column_name = 'approval_request_id' THEN '审批请求 ID 预留，用于后续接入安全中心审批流。'
      WHEN column_record.table_name = 'system_setting_snapshot' AND column_record.column_name = 'rollback_from_snapshot_id' THEN '回滚来源快照 ID。'
      WHEN column_record.table_name = 'system_setting_snapshot' AND column_record.column_name = 'rollback_count' THEN '该快照被用于回滚的次数。'
      WHEN column_record.table_name = 'system_setting_snapshot' AND column_record.column_name = 'impact_level' THEN '变更影响等级快照，LOW、MEDIUM、HIGH。'
      WHEN column_record.table_name = 'system_setting_snapshot' AND column_record.column_name = 'impact_summary' THEN '变更影响摘要快照。'
      WHEN column_record.table_name = 'approval_audit_event' AND column_record.column_name = 'source_type' THEN '审批来源类型，例如 TOOL_APPROVAL、NOTIFICATION_POLICY。'
      WHEN column_record.table_name = 'approval_audit_event' AND column_record.column_name = 'source_id' THEN '审批来源记录 ID。'
      WHEN column_record.table_name = 'approval_audit_event' AND column_record.column_name = 'event_type' THEN '审批事件类型，例如 REQUEST_CREATED、APPROVED、REJECTED、APPLIED、EXECUTION_FAILED。'
      WHEN column_record.table_name = 'approval_audit_event' AND column_record.column_name = 'event_status' THEN '审批事件状态，INFO、SUCCESS、FAILED、WARNING。'
      WHEN column_record.table_name = 'approval_audit_event' AND column_record.column_name = 'title' THEN '审批事件标题。'
      WHEN column_record.table_name = 'approval_audit_event' AND column_record.column_name = 'note' THEN '审批事件备注或决策说明。'
      WHEN column_record.table_name = 'approval_audit_event' AND column_record.column_name = 'request_id' THEN '关联请求 ID。'
      WHEN column_record.table_name = 'approval_audit_event' AND column_record.column_name = 'trace_id' THEN '关联链路 Trace ID。'
      WHEN column_record.table_name = 'approval_audit_event' AND column_record.column_name = 'metadata' THEN '审批事件扩展元数据。'
      WHEN column_record.table_name = 'approval_audit_event' AND column_record.column_name = 'actor_id' THEN '触发审批事件的用户 ID。'
      WHEN column_record.table_name = 'approval_audit_event' AND column_record.column_name = 'occurred_at' THEN '审批事件发生时间。'
      WHEN column_record.table_name = 'plugin' AND column_record.column_name = 'owner_id' THEN '插件负责人用户 ID。'
      WHEN column_record.table_name = 'plugin' AND column_record.column_name = 'provider' THEN '插件提供方。'
      WHEN column_record.table_name = 'plugin' AND column_record.column_name = 'source_type' THEN '插件来源类型，MARKET 市场插件、CUSTOM 自定义插件。'
      WHEN column_record.table_name = 'plugin' AND column_record.column_name = 'latest_version' THEN '插件最新版本号。'
      WHEN column_record.table_name = 'plugin' AND column_record.column_name = 'risk_level' THEN '插件风险等级，LOW、MEDIUM、HIGH、CRITICAL。'
      WHEN column_record.table_name = 'plugin' AND column_record.column_name = 'manifest_json' THEN '插件声明清单 JSON，包含入口、能力、Hook、菜单和权限声明。'
      WHEN column_record.table_name = 'plugin' AND column_record.column_name = 'config_json' THEN '插件默认配置 JSON。'
      WHEN column_record.table_name = 'plugin' AND column_record.column_name = 'permission_preview' THEN '插件声明权限编码预览 JSON 数组。'
      WHEN column_record.table_name = 'plugin' AND column_record.column_name = 'runtime_status' THEN '插件运行状态，RUNNING、STOPPED、UPGRADING、BLOCKED、ERROR。'
      WHEN column_record.table_name = 'plugin' AND column_record.column_name = 'menu_count' THEN '插件声明或绑定的菜单数量。'
      WHEN column_record.table_name = 'plugin' AND column_record.column_name = 'hook_count' THEN '插件声明或绑定的 Hook 数量。'
      WHEN column_record.table_name = 'plugin' AND column_record.column_name = 'audit_count' THEN '插件审计记录数量。'
      WHEN column_record.table_name = 'plugin' AND column_record.column_name = 'installed_at' THEN '插件安装时间。'
      WHEN column_record.table_name = 'plugin' AND column_record.column_name = 'last_upgraded_at' THEN '最近升级时间。'
      WHEN column_record.table_name = 'plugin' AND column_record.column_name = 'enabled_at' THEN '最近启用时间。'
      WHEN column_record.table_name = 'plugin' AND column_record.column_name = 'disabled_at' THEN '最近停用时间。'
      WHEN column_record.table_name = 'plugin_version' AND column_record.column_name = 'plugin_id' THEN '关联插件 ID。'
      WHEN column_record.table_name = 'plugin_version' AND column_record.column_name = 'manifest_json' THEN '该版本插件 Manifest 快照 JSON。'
      WHEN column_record.table_name = 'plugin_version' AND column_record.column_name = 'change_note' THEN '版本变更说明。'
      WHEN column_record.table_name = 'plugin_installation' AND column_record.column_name = 'plugin_id' THEN '关联插件 ID。'
      WHEN column_record.table_name = 'plugin_installation' AND column_record.column_name = 'owner_id' THEN '安装实例负责人用户 ID。'
      WHEN column_record.table_name = 'plugin_installation' AND column_record.column_name = 'installed_version' THEN '当前安装版本号。'
      WHEN column_record.table_name = 'plugin_installation' AND column_record.column_name = 'latest_version' THEN '可用最新版本号。'
      WHEN column_record.table_name = 'plugin_installation' AND column_record.column_name = 'runtime_status' THEN '运行状态，RUNNING、STOPPED、UPGRADING、BLOCKED、ERROR。'
      WHEN column_record.table_name = 'plugin_installation' AND column_record.column_name = 'source_type' THEN '插件来源类型，MARKET 市场插件、CUSTOM 自定义插件。'
      WHEN column_record.table_name = 'plugin_installation' AND column_record.column_name = 'risk_level' THEN '插件风险等级。'
      WHEN column_record.table_name = 'plugin_installation' AND column_record.column_name = 'config_json' THEN '租户安装实例配置 JSON。'
      WHEN column_record.table_name = 'plugin_installation' AND column_record.column_name = 'manifest_json' THEN '安装时插件 Manifest 快照 JSON。'
      WHEN column_record.table_name = 'plugin_installation' AND column_record.column_name = 'permission_preview' THEN '安装实例权限编码预览 JSON 数组。'
      WHEN column_record.table_name = 'plugin_installation' AND column_record.column_name = 'installed_at' THEN '安装时间。'
      WHEN column_record.table_name = 'plugin_installation' AND column_record.column_name = 'last_upgraded_at' THEN '最近升级时间。'
      WHEN column_record.table_name = 'plugin_installation' AND column_record.column_name = 'enabled_at' THEN '最近启用时间。'
      WHEN column_record.table_name = 'plugin_installation' AND column_record.column_name = 'disabled_at' THEN '最近停用时间。'
      WHEN column_record.table_name = 'plugin_hook' AND column_record.column_name = 'plugin_id' THEN '关联插件 ID。'
      WHEN column_record.table_name = 'plugin_hook' AND column_record.column_name = 'hook_type' THEN 'Hook 类型，例如 EVENT、USAGE、MENU、TOOL_GATEWAY、SECURITY。'
      WHEN column_record.table_name = 'plugin_hook' AND column_record.column_name = 'target' THEN 'Hook 目标事件、扩展点或内部主题。'
      WHEN column_record.table_name = 'plugin_hook' AND column_record.column_name = 'method' THEN 'Hook 调用方式，例如 SYNC、ASYNC、SCHEDULED、WEBHOOK。'
      WHEN column_record.table_name = 'plugin_hook' AND column_record.column_name = 'config_json' THEN 'Hook 配置 JSON。'
      WHEN column_record.table_name = 'plugin_menu_binding' AND column_record.column_name = 'plugin_id' THEN '关联插件 ID。'
      WHEN column_record.table_name = 'plugin_menu_binding' AND column_record.column_name = 'enabled' THEN '菜单绑定是否启用。'
      WHEN column_record.table_name = 'plugin_menu_binding' AND column_record.column_name = 'visible' THEN '菜单绑定是否可见。'
      WHEN column_record.table_name = 'plugin_menu_binding' AND column_record.column_name = 'sort_order' THEN '菜单绑定排序号。'
      WHEN column_record.table_name = 'plugin_audit_log' AND column_record.column_name = 'plugin_id' THEN '关联插件 ID。'
      WHEN column_record.table_name = 'plugin_audit_log' AND column_record.column_name = 'action' THEN '插件操作动作，例如 INSTALL、ENABLE、DISABLE、UPGRADE、HOOK_UPDATE、MENU_BINDING_UPDATE。'
      WHEN column_record.table_name = 'plugin_audit_log' AND column_record.column_name = 'title' THEN '审计标题。'
      WHEN column_record.table_name = 'plugin_audit_log' AND column_record.column_name = 'summary' THEN '审计摘要。'
      WHEN column_record.table_name = 'plugin_audit_log' AND column_record.column_name = 'risk_level' THEN '操作风险等级。'
      WHEN column_record.table_name = 'plugin_audit_log' AND column_record.column_name = 'payload_json' THEN '审计扩展负载 JSON。'
      WHEN column_record.column_name = 'last_used_at' THEN '最近使用时间。'
      WHEN column_record.column_name = 'last_login_at' THEN '最近登录时间。'
      WHEN column_record.column_name = 'created_at' THEN '创建时间。'
      WHEN column_record.column_name = 'updated_at' THEN '更新时间。'
      WHEN column_record.column_name = 'deleted_at' THEN '软删除时间。'
      WHEN column_record.column_name = 'expires_at' THEN '过期时间。'
      WHEN column_record.column_name = 'revoked_at' THEN '撤销时间。'
      WHEN column_record.column_name = 'module' THEN '所属模块。'
      WHEN column_record.table_name = 'permission' AND column_record.column_name = 'resource' THEN '权限资源编码，配合 module 和 action 组成 module:resource:action 标准权限编码。'
      WHEN column_record.column_name = 'resource' THEN '被访问资源属性 JSON。'
      WHEN column_record.column_name = 'action' THEN '动作类型。'
      WHEN column_record.column_name = 'effect' THEN '策略效果，ALLOW 表示允许，DENY 表示拒绝。'
      WHEN column_record.table_name IN ('platform_event', 'platform_usage_event') AND column_record.column_name = 'resource_type' THEN '事件或用量关联资源类型，例如 AGENT、AGENT_TEAM、TOOL、KNOWLEDGE_BASE、MODEL、PLUGIN、CHANNEL。'
      WHEN column_record.table_name IN ('platform_event', 'platform_usage_event') AND column_record.column_name = 'resource_id' THEN '事件或用量关联资源 ID，可为业务 UUID 或外部资源标识。'
      WHEN column_record.table_name = 'platform_usage_event' AND column_record.column_name = 'subject_type' THEN '用量主体类型，例如 USER、API_KEY、AGENT、AGENT_TEAM、PLUGIN、CHANNEL。'
      WHEN column_record.table_name = 'platform_usage_event' AND column_record.column_name = 'subject_id' THEN '用量主体 ID。'
      WHEN column_record.table_name = 'platform_event_relation' AND column_record.column_name = 'relation_type' THEN '关系类型，例如 TRACE_PARENT、REQUEST、SOURCE_LINK、USAGE_LINK、HANDOFF、APPROVAL、ROLLUP。'
      WHEN column_record.table_name = 'platform_event_relation' AND column_record.column_name = 'parent_event_id' THEN '父事件 ID。'
      WHEN column_record.table_name = 'platform_event_relation' AND column_record.column_name = 'child_event_id' THEN '子事件 ID。'
      WHEN column_record.table_name = 'platform_event_relation' AND column_record.column_name = 'source_event_id' THEN '源事件 ID。'
      WHEN column_record.table_name = 'platform_event_relation' AND column_record.column_name = 'target_event_id' THEN '目标事件 ID。'
      WHEN column_record.table_name = 'platform_event_relation' AND column_record.column_name = 'relation_source' THEN '关系来源系统或来源表。'
      WHEN column_record.table_name = 'platform_event_relation' AND column_record.column_name = 'relation_key' THEN '关系幂等键或外部关联键。'
      WHEN column_record.table_name = 'platform_event_relation' AND column_record.column_name = 'metadata' THEN '关系扩展元数据 JSON。'
      WHEN column_record.table_name = 'platform_event_relation' AND column_record.column_name = 'occurred_at' THEN '关系发生时间。'
      WHEN column_record.table_name = 'platform_usage_rollup' AND column_record.column_name = 'subject_type' THEN '汇总主体类型。'
      WHEN column_record.table_name = 'platform_usage_rollup' AND column_record.column_name = 'subject_id' THEN '汇总主体 ID。'
      WHEN column_record.table_name = 'platform_usage_rollup' AND column_record.column_name = 'period_type' THEN '汇总周期类型，hour 或 day。'
      WHEN column_record.table_name = 'platform_usage_rollup' AND column_record.column_name = 'period_start' THEN '汇总周期开始时间。'
      WHEN column_record.table_name = 'platform_usage_rollup' AND column_record.column_name = 'period_end' THEN '汇总周期结束时间。'
      WHEN column_record.table_name = 'platform_usage_rollup' AND column_record.column_name = 'event_count' THEN '事件数量。'
      WHEN column_record.table_name = 'platform_usage_rollup' AND column_record.column_name = 'quantity_total' THEN '数量总和。'
      WHEN column_record.table_name = 'platform_usage_rollup' AND column_record.column_name = 'amount_total' THEN '金额总和。'
      WHEN column_record.table_name = 'platform_usage_rollup' AND column_record.column_name = 'cost_total' THEN '成本总和。'
      WHEN column_record.table_name = 'platform_usage_rollup' AND column_record.column_name = 'error_count' THEN '错误数量。'
      WHEN column_record.table_name = 'platform_usage_rollup' AND column_record.column_name = 'success_count' THEN '成功数量。'
      WHEN column_record.table_name = 'platform_usage_rollup' AND column_record.column_name = 'retry_count' THEN '重试数量。'
      WHEN column_record.table_name = 'platform_usage_rollup' AND column_record.column_name = 'created_at' THEN '汇总记录创建时间。'
      WHEN column_record.table_name = 'platform_usage_rollup' AND column_record.column_name = 'updated_at' THEN '汇总记录更新时间。'
      WHEN column_record.table_name = 'billing_plan' AND column_record.column_name = 'tier' THEN '套餐层级，FREE、TEAM、BUSINESS、ENTERPRISE。'
      WHEN column_record.table_name = 'billing_plan' AND column_record.column_name = 'monthly_base_price' THEN '月付基础价格。'
      WHEN column_record.table_name = 'billing_plan' AND column_record.column_name = 'yearly_base_price' THEN '年付基础价格。'
      WHEN column_record.table_name = 'billing_plan' AND column_record.column_name = 'included_monthly_cost' THEN '套餐每月包含的模型或运行成本额度。'
      WHEN column_record.table_name = 'billing_plan' AND column_record.column_name = 'included_monthly_tokens' THEN '套餐每月包含词元数。'
      WHEN column_record.table_name = 'billing_plan' AND column_record.column_name = 'included_monthly_calls' THEN '套餐每月包含调用次数。'
      WHEN column_record.table_name = 'billing_plan' AND column_record.column_name = 'included_storage_gb' THEN '套餐包含存储容量 GB。'
      WHEN column_record.table_name = 'billing_plan' AND column_record.column_name = 'overage_unit_price' THEN '超额计价单价。'
      WHEN column_record.table_name = 'billing_plan' AND column_record.column_name = 'feature_limits' THEN '功能限制 JSON，例如 Agent、API Key、插件、协作团队数量。'
      WHEN column_record.table_name = 'tenant_subscription' AND column_record.column_name = 'plan_id' THEN '关联套餐 ID。'
      WHEN column_record.table_name = 'tenant_subscription' AND column_record.column_name = 'billing_cycle' THEN '计费周期，MONTHLY 或 YEARLY。'
      WHEN column_record.table_name = 'tenant_subscription' AND column_record.column_name = 'base_price' THEN '当前订阅周期基础价格。'
      WHEN column_record.table_name = 'tenant_subscription' AND column_record.column_name = 'included_monthly_cost' THEN '当前订阅每月包含成本额度。'
      WHEN column_record.table_name = 'tenant_subscription' AND column_record.column_name = 'included_monthly_tokens' THEN '当前订阅每月包含词元数。'
      WHEN column_record.table_name = 'tenant_subscription' AND column_record.column_name = 'included_monthly_calls' THEN '当前订阅每月包含调用次数。'
      WHEN column_record.table_name = 'tenant_subscription' AND column_record.column_name = 'current_period_start' THEN '当前账期开始时间。'
      WHEN column_record.table_name = 'tenant_subscription' AND column_record.column_name = 'current_period_end' THEN '当前账期结束时间。'
      WHEN column_record.table_name = 'tenant_subscription' AND column_record.column_name = 'trial_ends_at' THEN '试用结束时间。'
      WHEN column_record.table_name = 'tenant_subscription' AND column_record.column_name = 'canceled_at' THEN '取消时间。'
      WHEN column_record.table_name = 'tenant_subscription' AND column_record.column_name = 'auto_renew' THEN '是否自动续费。'
      WHEN column_record.table_name = 'billing_invoice' AND column_record.column_name = 'subscription_id' THEN '关联订阅 ID。'
      WHEN column_record.table_name = 'billing_invoice' AND column_record.column_name = 'invoice_no' THEN '账单编号，在租户内唯一。'
      WHEN column_record.table_name = 'billing_invoice' AND column_record.column_name = 'subtotal_amount' THEN '账单小计金额。'
      WHEN column_record.table_name = 'billing_invoice' AND column_record.column_name = 'discount_amount' THEN '优惠金额。'
      WHEN column_record.table_name = 'billing_invoice' AND column_record.column_name = 'tax_amount' THEN '税费金额。'
      WHEN column_record.table_name = 'billing_invoice' AND column_record.column_name = 'total_amount' THEN '账单总金额。'
      WHEN column_record.table_name = 'billing_invoice' AND column_record.column_name = 'paid_amount' THEN '已支付金额。'
      WHEN column_record.table_name = 'billing_invoice' AND column_record.column_name = 'period_start' THEN '账期开始时间。'
      WHEN column_record.table_name = 'billing_invoice' AND column_record.column_name = 'period_end' THEN '账期结束时间。'
      WHEN column_record.table_name = 'billing_invoice' AND column_record.column_name = 'due_at' THEN '账单到期时间。'
      WHEN column_record.table_name = 'billing_invoice' AND column_record.column_name = 'paid_at' THEN '账单支付时间。'
      WHEN column_record.table_name = 'billing_invoice' AND column_record.column_name = 'line_items' THEN '账单明细 JSON。'
      WHEN column_record.table_name = 'billing_quota_policy' AND column_record.column_name = 'name' THEN '额度策略名称。'
      WHEN column_record.table_name = 'billing_quota_policy' AND column_record.column_name = 'subject_type' THEN '额度主体类型，TENANT、API_KEY、AGENT、MODEL、PLUGIN。'
      WHEN column_record.table_name = 'billing_quota_policy' AND column_record.column_name = 'subject_id' THEN '额度主体 ID，租户级策略可为空。'
      WHEN column_record.table_name = 'billing_quota_policy' AND column_record.column_name = 'metric_type' THEN '额度指标类型，COST、TOKEN、MODEL_CALL、API_CALL、AGENT_RUN、STORAGE_GB。'
      WHEN column_record.table_name = 'billing_quota_policy' AND column_record.column_name = 'period' THEN '额度统计周期，DAY 或 MONTH。'
      WHEN column_record.table_name = 'billing_quota_policy' AND column_record.column_name = 'limit_value' THEN '额度上限值。'
      WHEN column_record.table_name = 'billing_quota_policy' AND column_record.column_name = 'warn_threshold' THEN '预警阈值百分比。'
      WHEN column_record.table_name = 'billing_quota_policy' AND column_record.column_name = 'hard_threshold' THEN '硬限制阈值百分比。'
      WHEN column_record.table_name = 'billing_quota_policy' AND column_record.column_name = 'action' THEN '达到阈值后的动作，WARN、THROTTLE、REQUIRE_APPROVAL、BLOCK。'
      WHEN column_record.table_name = 'billing_quota_policy' AND column_record.column_name = 'last_evaluated_at' THEN '最近评估时间。'
      WHEN column_record.column_name = 'resource_type' THEN '资源类型，例如 AGENT、KNOWLEDGE_BASE、DOCUMENT、TOOL、MODEL、CONVERSATION、AUDIT_LOG。'
      WHEN column_record.column_name = 'resource_id' THEN '被授权资源 ID。'
      WHEN column_record.column_name = 'subject_type' THEN '授权主体类型，USER 用户、ROLE 角色、DEPARTMENT 部门、TENANT 租户。'
      WHEN column_record.column_name = 'subject_id' THEN '授权主体 ID。'
      WHEN column_record.column_name = 'scope_type' THEN '数据范围类型，ALL 全部数据、TENANT 本租户、DEPT 本部门、DEPT_AND_CHILD 本部门及子部门、SELF 本人、CUSTOM 自定义。'
      WHEN column_record.column_name = 'scope_value' THEN '数据范围配置 JSON，包含 department_ids、user_ids、resource_ids、include_children 等自定义范围。'
      WHEN column_record.column_name = 'priority' THEN '策略优先级，数值越大越先匹配。'
      WHEN column_record.column_name = 'conditions' THEN 'ABAC 条件 JSON，包含 subject、resource、context 属性路径与操作符。'
      WHEN column_record.column_name = 'subject' THEN '访问主体属性 JSON。'
      WHEN column_record.column_name = 'decision' THEN '策略评估结果。'
      WHEN column_record.column_name = 'matched_policy_id' THEN '命中的安全策略 ID。'
      WHEN column_record.column_name = 'matched_policy_code' THEN '命中的安全策略编码快照。'
      WHEN column_record.column_name = 'method' THEN 'HTTP 方法。'
      WHEN column_record.column_name = 'path' THEN '请求路径。'
      WHEN column_record.column_name = 'status_code' THEN 'HTTP 状态码。'
      WHEN column_record.column_name = 'request_id' THEN '请求链路 ID。'
      WHEN column_record.column_name = 'ip' THEN '客户端 IP 地址。'
      WHEN column_record.column_name = 'user_agent' THEN '客户端标识。'
      WHEN column_record.column_name = 'request_summary' THEN '请求摘要 JSON。'
      WHEN column_record.column_name = 'error_message' THEN '错误信息。'
      WHEN column_record.column_name = 'decision_note' THEN '审批备注。'
      WHEN column_record.column_name = 'token_hash' THEN '令牌哈希值。'
      WHEN column_record.column_name = 'version' THEN '版本号。'
      WHEN column_record.column_name = 'snapshot' THEN '快照数据 JSON。'
      WHEN column_record.column_name = 'change_note' THEN '变更说明。'
      WHEN column_record.column_name = 'published_at' THEN '发布时间。'
      WHEN column_record.column_name = 'model_id' THEN '关联模型标识。'
      WHEN column_record.column_name = 'binding_type' THEN '绑定类型。'
      WHEN column_record.column_name = 'weight' THEN '权重值。'
      WHEN column_record.column_name = 'prompt_id' THEN '关联提示词标识。'
      WHEN column_record.column_name = 'prompt_type' THEN '提示词类型。'
      WHEN column_record.column_name = 'recall_top_k' THEN '召回 TopK 数量。'
      WHEN column_record.column_name = 'require_approval' THEN '是否需要审批。'
      WHEN column_record.column_name = 'channel' THEN '渠道标识。'
      WHEN column_record.table_name = 'agent_publish_channel' AND column_record.column_name = 'channel' THEN '渠道类型，WEB_WIDGET、OPEN_API、WECHAT_WORK、DINGTALK、FEISHU、SLACK、CUSTOM_WEBHOOK。'
      WHEN column_record.table_name = 'agent_publish_channel' AND column_record.column_name = 'endpoint_url' THEN '渠道入口地址，例如 Web Widget 地址、开放 API 地址或第三方机器人入口。'
      WHEN column_record.table_name = 'agent_publish_channel' AND column_record.column_name = 'callback_url' THEN '渠道回调地址，用于接收第三方平台事件或消息回调。'
      WHEN column_record.table_name = 'agent_publish_channel' AND column_record.column_name = 'secret_encrypted' THEN '渠道密钥密文，用于第三方平台签名或回调校验。'
      WHEN column_record.table_name = 'agent_publish_channel' AND column_record.column_name = 'secret_masked' THEN '渠道密钥脱敏展示值。'
      WHEN column_record.table_name = 'agent_publish_channel' AND column_record.column_name = 'last_published_at' THEN '最近发布时间。'
      WHEN column_record.table_name = 'agent_publish_channel' AND column_record.column_name = 'last_checked_at' THEN '最近健康检查时间。'
      WHEN column_record.table_name = 'agent_publish_channel' AND column_record.column_name = 'health_status' THEN '渠道健康状态，UNKNOWN、HEALTHY、DEGRADED、UNAVAILABLE。'
      WHEN column_record.table_name = 'agent_publish_channel' AND column_record.column_name = 'health_message' THEN '渠道健康检查说明或最近错误。'
      WHEN column_record.table_name = 'channel_sender_delivery' AND column_record.column_name = 'channel_id' THEN '关联发布渠道 ID。'
      WHEN column_record.table_name = 'channel_sender_delivery' AND column_record.column_name = 'agent_id' THEN '关联智能体 ID。'
      WHEN column_record.table_name = 'channel_sender_delivery' AND column_record.column_name = 'delivery_id' THEN '投递记录业务 ID。'
      WHEN column_record.table_name = 'channel_sender_delivery' AND column_record.column_name = 'parent_delivery_id' THEN '父级投递记录 ID，用于重试链路。'
      WHEN column_record.table_name = 'channel_sender_delivery' AND column_record.column_name = 'provider' THEN '渠道提供方标识，例如 WECHAT_WORK、DINGTALK、FEISHU、SLACK、CUSTOM_WEBHOOK。'
      WHEN column_record.table_name = 'channel_sender_delivery' AND column_record.column_name = 'target' THEN '发送目标，例如用户、群聊、Webhook 地址或频道标识。'
      WHEN column_record.table_name = 'channel_sender_delivery' AND column_record.column_name = 'request_url' THEN '实际投递请求地址，用于失败重试，前端展示时必须脱敏。'
      WHEN column_record.table_name = 'channel_sender_delivery' AND column_record.column_name = 'status' THEN '投递状态，PENDING、SUCCESS、FAILED、SKIPPED、RETRYING。'
      WHEN column_record.table_name = 'channel_sender_delivery' AND column_record.column_name = 'response_status' THEN '接收方响应状态码。'
      WHEN column_record.table_name = 'channel_sender_delivery' AND column_record.column_name = 'response_body' THEN '接收方响应正文截断。'
      WHEN column_record.table_name = 'channel_sender_delivery' AND column_record.column_name = 'request_body' THEN '发送请求正文 JSON。'
      WHEN column_record.table_name = 'channel_sender_delivery' AND column_record.column_name = 'request_headers' THEN '发送请求头 JSON。'
      WHEN column_record.table_name = 'channel_sender_delivery' AND column_record.column_name = 'error_message' THEN '发送失败原因。'
      WHEN column_record.table_name = 'channel_sender_delivery' AND column_record.column_name = 'retry_count' THEN '重试次数。'
      WHEN column_record.table_name = 'channel_sender_delivery' AND column_record.column_name = 'latency_ms' THEN '投递耗时毫秒数。'
      WHEN column_record.table_name = 'channel_sender_delivery' AND column_record.column_name = 'conversation_id' THEN '关联会话 ID。'
      WHEN column_record.table_name = 'channel_sender_delivery' AND column_record.column_name = 'run_id' THEN '关联运行 ID。'
      WHEN column_record.table_name = 'channel_sender_delivery' AND column_record.column_name = 'trace_id' THEN '关联 Trace ID。'
      WHEN column_record.table_name = 'channel_sender_delivery' AND column_record.column_name = 'external_conversation_id' THEN '外部平台会话 ID。'
      WHEN column_record.table_name = 'channel_sender_delivery' AND column_record.column_name = 'external_message_id' THEN '外部平台消息 ID。'
      WHEN column_record.table_name = 'channel_sender_delivery' AND column_record.column_name = 'delivered_at' THEN '实际投递完成时间。'
      WHEN column_record.column_name = 'config' THEN '配置 JSON。'
      WHEN column_record.column_name = 'message' THEN '消息内容。'
      WHEN column_record.column_name = 'metadata' THEN '附加元数据 JSON。'
      WHEN column_record.column_name = 'provider_type' THEN '供应商类型。'
      WHEN column_record.column_name = 'base_url' THEN '基础调用地址。'
      WHEN column_record.column_name = 'is_default' THEN '是否默认。'
      WHEN column_record.column_name = 'model' THEN '模型标识。'
      WHEN column_record.column_name = 'capabilities' THEN '能力列表。'
      WHEN column_record.column_name = 'context_length' THEN '上下文长度。'
      WHEN column_record.column_name = 'input_price' THEN '输入价格。'
      WHEN column_record.column_name = 'output_price' THEN '输出价格。'
      WHEN column_record.column_name = 'rate_limit_rpm' THEN '每分钟限流。'
      WHEN column_record.column_name = 'masked_key' THEN '脱敏后的密钥。'
      WHEN column_record.column_name = 'encrypted_key' THEN '加密后的密钥。'
      WHEN column_record.column_name = 'currency' THEN '货币类型。'
      WHEN column_record.column_name = 'unit' THEN '计费单位。'
      WHEN column_record.column_name = 'effective_from' THEN '生效时间。'
      WHEN column_record.column_name = 'trace_id' THEN '追踪链路 ID。'
      WHEN column_record.column_name = 'actor_type' THEN '事件触发主体类型，例如 USER、API_KEY、SYSTEM、RUNTIME、WORKFLOW。'
      WHEN column_record.column_name = 'plugin_id' THEN '事件关联插件 ID。'
      WHEN column_record.column_name = 'channel_id' THEN '事件关联发布渠道 ID。'
      WHEN column_record.column_name = 'task_id' THEN '事件关联任务 ID，例如后台任务或工作流任务。'
      WHEN column_record.column_name = 'parent_trace_id' THEN '父级追踪链路 ID，用于关联重试、接力或子任务。'
      WHEN column_record.column_name = 'event_source' THEN '事件来源模块，例如 CONTROL_API、RUNTIME、AGENT_TEAM、TOOL_GATEWAY、TEMPORAL。'
      WHEN column_record.column_name = 'event_type' THEN '事件类型编码，例如 agent.team.run.finished、agent.team.handoff。'
      WHEN column_record.column_name = 'severity' THEN '事件严重级别，例如 INFO、WARN、ERROR。'
      WHEN column_record.column_name = 'security_level' THEN '安全等级，例如 PUBLIC、INTERNAL、CONFIDENTIAL、SECRET。'
      WHEN column_record.column_name = 'billable' THEN '是否参与计费或用量归因。'
      WHEN column_record.column_name = 'summary' THEN '摘要文本。'
      WHEN column_record.column_name = 'payload_json' THEN '事件扩展负载 JSON。'
      WHEN column_record.column_name = 'occurred_at' THEN '实际发生时间。'
      WHEN column_record.column_name = 'source_system' THEN '事实来源系统或来源表名。'
      WHEN column_record.column_name = 'source_id' THEN '事实来源记录 ID。'
      WHEN column_record.column_name = 'dedupe_key' THEN '事件幂等去重键。'
      WHEN column_record.column_name = 'metric_type' THEN '用量指标类型，例如 model_tokens、workflow_steps、agent_team_runs。'
      WHEN column_record.column_name = 'quantity' THEN '用量数量。'
      WHEN column_record.column_name = 'unit_price' THEN '单位价格。'
      WHEN column_record.column_name = 'amount' THEN '用量金额。'
      WHEN column_record.column_name = 'cost_source' THEN '成本来源或计价来源，例如 AGENT_TEAM_RUNTIME、MODEL_PROVIDER。'
      WHEN column_record.column_name = 'event_id' THEN '关联的平台事件 ID。'
      WHEN column_record.column_name = 'request_model' THEN '请求使用的模型标识。'
      WHEN column_record.column_name = 'prompt_tokens' THEN '输入词元数。'
      WHEN column_record.column_name = 'completion_tokens' THEN '输出词元数。'
      WHEN column_record.column_name = 'total_tokens' THEN '总词元数。'
      WHEN column_record.column_name = 'input_cost' THEN '输入成本。'
      WHEN column_record.column_name = 'output_cost' THEN '输出成本。'
      WHEN column_record.column_name = 'total_cost' THEN '总成本。'
      WHEN column_record.column_name = 'latency_ms' THEN '延迟毫秒数。'
      WHEN column_record.column_name = 'response_summary' THEN '响应摘要 JSON。'
      WHEN column_record.column_name = 'type' THEN '类型。'
      WHEN column_record.column_name = 'content' THEN '内容。'
      WHEN column_record.column_name = 'variable_type' THEN '变量类型。'
      WHEN column_record.column_name = 'default_value' THEN '默认值。'
      WHEN column_record.column_name = 'is_required' THEN '是否必填。'
      WHEN column_record.column_name = 'sort_order' THEN '排序号。'
      WHEN column_record.column_name = 'inputs' THEN '输入参数 JSON。'
      WHEN column_record.column_name = 'rendered_content' THEN '渲染后的内容。'
      WHEN column_record.column_name = 'output_text' THEN '输出文本。'
      WHEN column_record.column_name = 'visibility' THEN '可见范围。'
      WHEN column_record.column_name = 'source_type' THEN '来源类型。'
      WHEN column_record.column_name = 'mime_type' THEN 'MIME 类型。'
      WHEN column_record.column_name = 'file_name' THEN '文件名。'
      WHEN column_record.column_name = 'file_size' THEN '文件大小（字节）。'
      WHEN column_record.column_name = 'storage_path' THEN '存储路径。'
      WHEN column_record.column_name = 'checksum' THEN '内容校验和。'
      WHEN column_record.column_name = 'parsed_text' THEN '解析后的文本内容。'
      WHEN column_record.column_name = 'segment_count' THEN '切片数量。'
      WHEN column_record.column_name = 'token_count' THEN '词元数量。'
      WHEN column_record.column_name = 'keywords' THEN '关键词数组。'
      WHEN column_record.column_name = 'embedding_vector' THEN '切片嵌入向量。'
      WHEN column_record.column_name = 'embedding_model' THEN '生成嵌入所使用的模型标识。'
      WHEN column_record.column_name = 'vector_status' THEN '向量状态。'
      WHEN column_record.column_name = 'index_status' THEN '索引状态。'
      WHEN column_record.column_name = 'task_type' THEN '任务类型。'
      WHEN column_record.column_name = 'total_items' THEN '总项目数量。'
      WHEN column_record.column_name = 'processed_items' THEN '已处理项目数量。'
      WHEN column_record.column_name = 'started_at' THEN '开始时间。'
      WHEN column_record.column_name = 'ended_at' THEN '结束时间。'
      WHEN column_record.column_name = 'reviewed_at' THEN '审批时间。'
      WHEN column_record.column_name = 'query' THEN '查询内容。'
      WHEN column_record.column_name = 'mode' THEN '模式。'
      WHEN column_record.column_name = 'max_rounds' THEN 'Agent 协作团队最大执行轮次。'
      WHEN column_record.column_name = 'timeout_seconds' THEN 'Agent 协作团队单次运行超时时间（秒）。'
      WHEN column_record.column_name = 'handoff_policy' THEN 'Agent 协作团队接力策略，AUTO 自动、MANUAL 人工、APPROVAL_REQUIRED 需审批。'
      WHEN column_record.column_name = 'responsibility' THEN '团队成员职责说明。'
      WHEN column_record.column_name = 'execution_order' THEN '团队成员执行顺序。'
      WHEN column_record.column_name = 'required' THEN '团队成员是否为必需成员。'
      WHEN column_record.column_name = 'objective' THEN '团队任务目标。'
      WHEN column_record.column_name = 'total_steps' THEN '团队运行总步骤数。'
      WHEN column_record.column_name = 'completed_steps' THEN '团队运行已完成步骤数。'
      WHEN column_record.column_name = 'failed_steps' THEN '团队运行失败步骤数。'
      WHEN column_record.column_name = 'step_type' THEN '团队运行步骤类型，例如 PLAN、AGENT_RUN、HANDOFF、VERIFY、SUMMARY。'
      WHEN column_record.column_name = 'title' THEN '标题。'
      WHEN column_record.column_name = 'input_summary' THEN '步骤输入摘要。'
      WHEN column_record.column_name = 'output_summary' THEN '步骤输出摘要。'
      WHEN column_record.column_name = 'span_id' THEN '当前步骤 Span ID。'
      WHEN column_record.column_name = 'parent_span_id' THEN '父级 Span ID。'
      WHEN column_record.column_name = 'duration_ms' THEN '步骤耗时毫秒数。'
      WHEN column_record.column_name = 'cost_total' THEN '步骤成本。'
      WHEN column_record.column_name = 'decided_by' THEN '接力决策人用户 ID。'
      WHEN column_record.column_name = 'decided_at' THEN '接力决策时间。'
      WHEN column_record.column_name = 'top_k' THEN 'Top K 数量。'
      WHEN column_record.column_name = 'result_count' THEN '结果数量。'
      WHEN column_record.column_name = 'results' THEN '结果明细 JSON。'
      WHEN column_record.column_name = 'tool_type' THEN '工具类型。'
      WHEN column_record.column_name = 'risk_level' THEN '风险等级。'
      WHEN column_record.column_name = 'timeout_ms' THEN '超时时间（毫秒）。'
      WHEN column_record.column_name = 'headers' THEN '默认请求头 JSON。'
      WHEN column_record.column_name = 'auth_type' THEN '鉴权类型。'
      WHEN column_record.column_name = 'auth_config' THEN '鉴权配置 JSON。'
      WHEN column_record.column_name = 'input_schema' THEN '输入结构 JSON Schema。'
      WHEN column_record.column_name = 'output_schema' THEN '输出结构 JSON Schema。'
      WHEN column_record.column_name = 'trigger_source' THEN '触发来源。'
      WHEN column_record.column_name = 'request_url' THEN '请求 URL。'
      WHEN column_record.column_name = 'request_method' THEN '请求方法。'
      WHEN column_record.column_name = 'request_headers' THEN '请求头 JSON。'
      WHEN column_record.column_name = 'request_body' THEN '请求体 JSON。'
      WHEN column_record.column_name = 'reason' THEN '申请原因。'
      WHEN column_record.column_name = 'response_status' THEN '响应状态码。'
      WHEN column_record.column_name = 'response_headers' THEN '响应头 JSON。'
      WHEN column_record.column_name = 'response_body' THEN '响应体 JSON。'
      WHEN column_record.column_name = 'message_count' THEN '消息数量。'
      WHEN column_record.column_name = 'last_message_preview' THEN '最近消息预览。'
      WHEN column_record.column_name = 'last_message_at' THEN '最近消息时间。'
      WHEN column_record.column_name = 'last_run_status' THEN '最近运行状态。'
      WHEN column_record.column_name = 'steps' THEN '运行步骤 JSON。'
      WHEN column_record.column_name = 'references' THEN '引用列表 JSON。'
      WHEN column_record.column_name = 'tool_calls' THEN '工具调用列表 JSON。'
      WHEN column_record.column_name = 'rating' THEN '评分。'
      WHEN column_record.column_name = 'comment' THEN '备注评论。'
      ELSE format('字段：%s。', column_record.column_name)
    END;

    EXECUTE format(
      'COMMENT ON COLUMN public.%I.%I IS %L',
      column_record.table_name,
      column_record.column_name,
      comment_text
    );
  END LOOP;
END $$;
