import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import test from 'node:test';

const p4ContentFiles = [
  'src/components/data-scopes/data-scope-content.tsx',
  'src/components/data-scopes/data-scope-detail-content.tsx',
  'src/components/data-scopes/data-scope-edit-content.tsx',
  'src/components/data-scopes/data-scope-shared.tsx',
  'src/components/agent-teams/agent-team-run-detail-content.tsx',
  'src/components/agent-teams/agent-team-members-content.tsx',
  'src/components/agent-teams/agent-team-report-archives-content.tsx',
  'src/components/agent-teams/agent-team-runs-content.tsx',
  'src/components/agent-teams/agent-team-run-step-detail-content.tsx',
  'src/components/agent-teams/agent-team-run-trace-graph.tsx',
  'src/components/agent-teams/agent-team-detail-content.tsx',
  'src/components/agents/agent-binding-manager.tsx',
  'src/components/agents/agent-edit-content.tsx',
  'src/components/api-keys/api-key-content.tsx',
  'src/components/api-keys/api-key-create-content.tsx',
  'src/components/billing/billing-content.tsx',
  'src/components/billing/billing-quota-policy-content.tsx',
  'src/components/billing/billing-subscription-content.tsx',
  'src/components/channels/channel-account-create-content.tsx',
  'src/components/channels/channel-account-edit-content.tsx',
  'src/components/channels/channel-accounts-content.tsx',
  'src/components/channels/channel-release-content.tsx',
  'src/components/channels/channel-release-shared.tsx',
  'src/components/channels/channel-job-detail-content.tsx',
  'src/components/channels/channel-route-rule-create-content.tsx',
  'src/components/channels/channel-route-rules-content.tsx',
  'src/components/channels/channel-template-create-content.tsx',
  'src/components/channels/channel-provider-create-content.tsx',
  'src/components/channels/channel-provider-edit-content.tsx',
  'src/components/channels/channel-provider-account-forms.tsx',
  'src/components/channels/channel-publish-content.tsx',
  'src/components/channels/channel-sender-delivery-detail-content.tsx',
  'src/components/channels/channel-sender-content.tsx',
  'src/components/channels/channel-reply-detail-content.tsx',
  'src/components/channels/channel-replies-content.tsx',
  'src/components/channels/channel-route-rule-edit-content.tsx',
  'src/components/channels/channel-release-gate-content.tsx',
  'src/components/channels/channel-release-automation-content.tsx',
  'src/components/channels/channel-release-scheduler-content.tsx',
  'src/components/channels/channel-release-self-healing-content.tsx',
  'src/components/channels/channel-release-pipeline-content.tsx',
  'src/components/channels/channel-release-control-content.tsx',
  'src/components/conversations/conversation-create-content.tsx',
  'src/components/conversations/conversation-run-trace-card.tsx',
  'src/components/customer-success-opportunities/customer-success-opportunity-analytics-content.tsx',
  'src/components/knowledge/knowledge-content.tsx',
  'src/components/knowledge/knowledge-detail-content.tsx',
  'src/components/knowledge/knowledge-documents-content.tsx',
  'src/components/knowledge/knowledge-edit-content.tsx',
  'src/components/knowledge/knowledge-health-content.tsx',
  'src/components/knowledge/knowledge-activity-content.tsx',
  'src/components/knowledge/knowledge-overview-shared.tsx',
  'src/components/plugins/plugin-detail-content.tsx',
  'src/components/plugins/plugin-installations-content.tsx',
  'src/components/plugins/plugin-bindings-content.tsx',
  'src/components/plugins/plugin-security-content.tsx',
  'src/components/approval-audits/approval-audit-archives-content.tsx',
  'src/components/approvals/archive-deletion-approvals-content.tsx',
  'src/components/approvals/notification-policy-approvals-content.tsx',
  'src/components/approvals/tool-approvals-content.tsx',
  'src/components/delivery-reviews/delivery-reviews-content.tsx',
  'src/components/departments/department-detail-content.tsx',
  'src/components/menus/menu-detail-content.tsx',
  'src/components/menus/menu-edit-content.tsx',
  'src/components/models/model-api-key-card.tsx',
  'src/components/models/model-cost-log-card.tsx',
  'src/components/models/model-provider-detail-header.tsx',
  'src/components/models/model-provider-edit-content.tsx',
  'src/components/modules/module-page-shell.tsx',
  'src/components/monitor/monitor-shared-panels.tsx',
  'src/components/prompts/prompt-edit-content.tsx',
  'src/components/resource-acls/resource-acl-content.tsx',
  'src/components/role-scenarios/role-scenario-form-panel.tsx',
  'src/components/roles/role-detail-content.tsx',
  'src/components/roles/role-menus-content.tsx',
  'src/components/roles/role-permissions-content.tsx',
  'src/components/security/security-alerts-content.tsx',
  'src/components/security/security-archives-content.tsx',
  'src/components/security/security-event-detail-content.tsx',
  'src/components/security/security-policies-content.tsx',
  'src/components/settings/settings-content.tsx',
  'src/components/skills/skill-form-panel.tsx',
  'src/components/solution-packages/solution-packages-content.tsx',
  'src/components/storage/storage-object-detail-content.tsx',
  'src/components/storage/storage-settings-content.tsx',
  'src/components/tenants/tenant-detail-content.tsx',
  'src/components/tools/tool-call-logs-card.tsx',
  'src/components/users/user-detail-content.tsx',
  'src/components/platform-event-usage/platform-usage-overview-content.tsx',
  'src/components/platform-event-usage/platform-usage-notifications-content.tsx',
  'src/components/platform-event-usage/platform-usage-shared.tsx',
  'src/components/platform-event-usage/platform-event-usage-panel.tsx',
];

const descriptivePatterns = [
  /列表页/,
  /主列表/,
  /详情页/,
  /独立于列表/,
  /对应模块/,
  /避免在/,
  /避免.*塞入/,
  /这里会/,
  /会在这里/,
  /集中查看/,
  /集中展示/,
  /集中管理/,
  /统一查看/,
  /查看.*完整/,
  /维护.*配置/,
  /新增表单/,
  /保存后返回/,
  /后续.*展示/,
  /当前页面/,
  /本页/,
  /从左侧选择/,
  /先选择/,
  /请先创建/,
  /Runtime 回写/,
];

test('p4 focused pages avoid long descriptive product copy', () => {
  for (const file of p4ContentFiles) {
    const source = readFileSync(join(process.cwd(), file), 'utf8');

    for (const pattern of descriptivePatterns) {
      assert.doesNotMatch(source, pattern, `${file} still exposes descriptive copy: ${pattern}`);
    }
  }
});
